// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/catalog.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_SyncFileVersions_FullMethodName      = "/catalogservice.CatalogService/SyncFileVersions"
	CatalogService_ListEntries_FullMethodName           = "/catalogservice.CatalogService/ListEntries"
	CatalogService_ListClientFacets_FullMethodName      = "/catalogservice.CatalogService/ListClientFacets"
	CatalogService_ListJobFacets_FullMethodName         = "/catalogservice.CatalogService/ListJobFacets"
	CatalogService_ListDirectoryFacets_FullMethodName   = "/catalogservice.CatalogService/ListDirectoryFacets"
	CatalogService_ListStoreFacets_FullMethodName       = "/catalogservice.CatalogService/ListStoreFacets"
	CatalogService_ListDirectoryChildren_FullMethodName = "/catalogservice.CatalogService/ListDirectoryChildren"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	SyncFileVersions(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*ListEntriesResponse, error)
	ListClientFacets(ctx context.Context, in *ListFacetsRequest, opts ...grpc.CallOption) (*ListFacetsResponse, error)
	ListJobFacets(ctx context.Context, in *ListFacetsRequest, opts ...grpc.CallOption) (*ListFacetsResponse, error)
	ListDirectoryFacets(ctx context.Context, in *ListFacetsRequest, opts ...grpc.CallOption) (*ListFacetsResponse, error)
	ListStoreFacets(ctx context.Context, in *ListFacetsRequest, opts ...grpc.CallOption) (*ListFacetsResponse, error)
	ListDirectoryChildren(ctx context.Context, in *ListDirectoryChildrenRequest, opts ...grpc.CallOption) (*ListDirectoryChildrenResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) SyncFileVersions(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, CatalogService_SyncFileVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListEntries(ctx context.Context, in *ListEntriesRequest, opts ...grpc.CallOption) (*ListEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntriesResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListClientFacets(ctx context.Context, in *ListFacetsRequest, opts ...grpc.CallOption) (*ListFacetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFacetsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListClientFacets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListJobFacets(ctx context.Context, in *ListFacetsRequest, opts ...grpc.CallOption) (*ListFacetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFacetsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListJobFacets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListDirectoryFacets(ctx context.Context, in *ListFacetsRequest, opts ...grpc.CallOption) (*ListFacetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFacetsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListDirectoryFacets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListStoreFacets(ctx context.Context, in *ListFacetsRequest, opts ...grpc.CallOption) (*ListFacetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFacetsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListStoreFacets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListDirectoryChildren(ctx context.Context, in *ListDirectoryChildrenRequest, opts ...grpc.CallOption) (*ListDirectoryChildrenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDirectoryChildrenResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListDirectoryChildren_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	SyncFileVersions(context.Context, *SyncRequest) (*SyncResponse, error)
	ListEntries(context.Context, *ListEntriesRequest) (*ListEntriesResponse, error)
	ListClientFacets(context.Context, *ListFacetsRequest) (*ListFacetsResponse, error)
	ListJobFacets(context.Context, *ListFacetsRequest) (*ListFacetsResponse, error)
	ListDirectoryFacets(context.Context, *ListFacetsRequest) (*ListFacetsResponse, error)
	ListStoreFacets(context.Context, *ListFacetsRequest) (*ListFacetsResponse, error)
	ListDirectoryChildren(context.Context, *ListDirectoryChildrenRequest) (*ListDirectoryChildrenResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) SyncFileVersions(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncFileVersions not implemented")
}
func (UnimplementedCatalogServiceServer) ListEntries(context.Context, *ListEntriesRequest) (*ListEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEntries not implemented")
}
func (UnimplementedCatalogServiceServer) ListClientFacets(context.Context, *ListFacetsRequest) (*ListFacetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClientFacets not implemented")
}
func (UnimplementedCatalogServiceServer) ListJobFacets(context.Context, *ListFacetsRequest) (*ListFacetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobFacets not implemented")
}
func (UnimplementedCatalogServiceServer) ListDirectoryFacets(context.Context, *ListFacetsRequest) (*ListFacetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDirectoryFacets not implemented")
}
func (UnimplementedCatalogServiceServer) ListStoreFacets(context.Context, *ListFacetsRequest) (*ListFacetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStoreFacets not implemented")
}
func (UnimplementedCatalogServiceServer) ListDirectoryChildren(context.Context, *ListDirectoryChildrenRequest) (*ListDirectoryChildrenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDirectoryChildren not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_SyncFileVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SyncFileVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SyncFileVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SyncFileVersions(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListEntries(ctx, req.(*ListEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListClientFacets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFacetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListClientFacets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListClientFacets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListClientFacets(ctx, req.(*ListFacetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListJobFacets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFacetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListJobFacets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListJobFacets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListJobFacets(ctx, req.(*ListFacetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListDirectoryFacets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFacetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListDirectoryFacets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListDirectoryFacets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListDirectoryFacets(ctx, req.(*ListFacetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListStoreFacets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFacetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListStoreFacets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListStoreFacets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListStoreFacets(ctx, req.(*ListFacetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListDirectoryChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectoryChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListDirectoryChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListDirectoryChildren_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListDirectoryChildren(ctx, req.(*ListDirectoryChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalogservice.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncFileVersions",
			Handler:    _CatalogService_SyncFileVersions_Handler,
		},
		{
			MethodName: "ListEntries",
			Handler:    _CatalogService_ListEntries_Handler,
		},
		{
			MethodName: "ListClientFacets",
			Handler:    _CatalogService_ListClientFacets_Handler,
		},
		{
			MethodName: "ListJobFacets",
			Handler:    _CatalogService_ListJobFacets_Handler,
		},
		{
			MethodName: "ListDirectoryFacets",
			Handler:    _CatalogService_ListDirectoryFacets_Handler,
		},
		{
			MethodName: "ListStoreFacets",
			Handler:    _CatalogService_ListStoreFacets_Handler,
		},
		{
			MethodName: "ListDirectoryChildren",
			Handler:    _CatalogService_ListDirectoryChildren_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/catalog.proto",
}
