// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/catalog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileVersionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Ctime         int64                  `protobuf:"varint,4,opt,name=ctime,proto3" json:"ctime,omitempty"`
	SourceSeq     int64                  `protobuf:"varint,5,opt,name=source_seq,json=sourceSeq,proto3" json:"source_seq,omitempty"` // bwfs's local file_versions.seq — informational only
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds; bwfs's original recording time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileVersionEntry) Reset() {
	*x = FileVersionEntry{}
	mi := &file_api_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileVersionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileVersionEntry) ProtoMessage() {}

func (x *FileVersionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileVersionEntry.ProtoReflect.Descriptor instead.
func (*FileVersionEntry) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *FileVersionEntry) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FileVersionEntry) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *FileVersionEntry) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FileVersionEntry) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *FileVersionEntry) GetSourceSeq() int64 {
	if x != nil {
		return x.SourceSeq
	}
	return 0
}

func (x *FileVersionEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileVersionEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRequest) GetEntries() []*FileVersionEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{2}
}

var File_api_catalog_proto protoreflect.FileDescriptor

const file_api_catalog_proto_rawDesc = "" +
	"\n" +
	"\x11api/catalog.proto\x12\x0ecatalogservice\"\xb6\x01\n" +
	"\x10FileVersionEntry\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\fR\bmetadata\x12\x14\n" +
	"\x05ctime\x18\x04 \x01(\x03R\x05ctime\x12\x1d\n" +
	"\n" +
	"source_seq\x18\x05 \x01(\x03R\tsourceSeq\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"I\n" +
	"\vSyncRequest\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .catalogservice.FileVersionEntryR\aentries\"\x0e\n" +
	"\fSyncResponse2_\n" +
	"\x0eCatalogService\x12M\n" +
	"\x10SyncFileVersions\x12\x1b.catalogservice.SyncRequest\x1a\x1c.catalogservice.SyncResponseB\tZ\a./protob\x06proto3"

var (
	file_api_catalog_proto_rawDescOnce sync.Once
	file_api_catalog_proto_rawDescData []byte
)

func file_api_catalog_proto_rawDescGZIP() []byte {
	file_api_catalog_proto_rawDescOnce.Do(func() {
		file_api_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_catalog_proto_rawDesc), len(file_api_catalog_proto_rawDesc)))
	})
	return file_api_catalog_proto_rawDescData
}

var file_api_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_catalog_proto_goTypes = []any{
	(*FileVersionEntry)(nil), // 0: catalogservice.FileVersionEntry
	(*SyncRequest)(nil),      // 1: catalogservice.SyncRequest
	(*SyncResponse)(nil),     // 2: catalogservice.SyncResponse
}
var file_api_catalog_proto_depIdxs = []int32{
	0, // 0: catalogservice.SyncRequest.entries:type_name -> catalogservice.FileVersionEntry
	1, // 1: catalogservice.CatalogService.SyncFileVersions:input_type -> catalogservice.SyncRequest
	2, // 2: catalogservice.CatalogService.SyncFileVersions:output_type -> catalogservice.SyncResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_catalog_proto_init() }
func file_api_catalog_proto_init() {
	if File_api_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_catalog_proto_rawDesc), len(file_api_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_catalog_proto_goTypes,
		DependencyIndexes: file_api_catalog_proto_depIdxs,
		MessageInfos:      file_api_catalog_proto_msgTypes,
	}.Build()
	File_api_catalog_proto = out.File
	file_api_catalog_proto_goTypes = nil
	file_api_catalog_proto_depIdxs = nil
}
