// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/catalog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileVersionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Ctime         int64                  `protobuf:"varint,4,opt,name=ctime,proto3" json:"ctime,omitempty"`
	StoreSeq      int64                  `protobuf:"varint,5,opt,name=store_seq,json=storeSeq,proto3" json:"store_seq,omitempty"`    // bwfs's local file_versions.seq — informational only
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds; bwfs's original recording time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileVersionEntry) Reset() {
	*x = FileVersionEntry{}
	mi := &file_api_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileVersionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileVersionEntry) ProtoMessage() {}

func (x *FileVersionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileVersionEntry.ProtoReflect.Descriptor instead.
func (*FileVersionEntry) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *FileVersionEntry) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FileVersionEntry) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *FileVersionEntry) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FileVersionEntry) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *FileVersionEntry) GetStoreSeq() int64 {
	if x != nil {
		return x.StoreSeq
	}
	return 0
}

func (x *FileVersionEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileVersionEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *SyncRequest) GetEntries() []*FileVersionEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{2}
}

type ListEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreHost     string                 `protobuf:"bytes,1,opt,name=store_host,json=storeHost,proto3" json:"store_host,omitempty"`              // exact match against the sending bwfs node's identity; empty = all
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`                                   // substring match against object_id; empty = no filter
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                      // 1..500, default 100
	StartingAfter int64                  `protobuf:"varint,4,opt,name=starting_after,json=startingAfter,proto3" json:"starting_after,omitempty"` // last-seen entry ID from a previous page; 0 = first page
	SourceHost    string                 `protobuf:"bytes,5,opt,name=source_host,json=sourceHost,proto3" json:"source_host,omitempty"`           // exact match against the real originating (backed-up) host; empty = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_api_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ListEntriesRequest) GetStoreHost() string {
	if x != nil {
		return x.StoreHost
	}
	return ""
}

func (x *ListEntriesRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *ListEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEntriesRequest) GetStartingAfter() int64 {
	if x != nil {
		return x.StartingAfter
	}
	return 0
}

func (x *ListEntriesRequest) GetSourceHost() string {
	if x != nil {
		return x.SourceHost
	}
	return ""
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_api_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListEntriesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type Entry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StoreHost      string                 `protobuf:"bytes,2,opt,name=store_host,json=storeHost,proto3" json:"store_host,omitempty"`
	JobId          string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ObjectId       string                 `protobuf:"bytes,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Ctime          int64                  `protobuf:"varint,5,opt,name=ctime,proto3" json:"ctime,omitempty"`
	StoreCreatedAt int64                  `protobuf:"varint,6,opt,name=store_created_at,json=storeCreatedAt,proto3" json:"store_created_at,omitempty"`
	ReceivedAt     int64                  `protobuf:"varint,7,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// decoded server-side from the stored Metadata blob:
	Path          string `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64  `protobuf:"varint,9,opt,name=size,proto3" json:"size,omitempty"`
	Mode          string `protobuf:"bytes,10,opt,name=mode,proto3" json:"mode,omitempty"`    // e.g. "-rw-r--r--", from fs.FileMode.String()
	Owner         uint32 `protobuf:"varint,11,opt,name=owner,proto3" json:"owner,omitempty"` // Unix UID (or Windows SID hash) — numeric, no name resolution
	Group         uint32 `protobuf:"varint,12,opt,name=group,proto3" json:"group,omitempty"` // Unix GID (or Windows SID hash) — numeric, no name resolution
	ModTime       int64  `protobuf:"varint,13,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	SourceHost    string `protobuf:"bytes,14,opt,name=source_host,json=sourceHost,proto3" json:"source_host,omitempty"` // the real originating (backed-up) host, derived from Metadata at sync time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_api_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_api_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_api_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *Entry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entry) GetStoreHost() string {
	if x != nil {
		return x.StoreHost
	}
	return ""
}

func (x *Entry) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Entry) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *Entry) GetCtime() int64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *Entry) GetStoreCreatedAt() int64 {
	if x != nil {
		return x.StoreCreatedAt
	}
	return 0
}

func (x *Entry) GetReceivedAt() int64 {
	if x != nil {
		return x.ReceivedAt
	}
	return 0
}

func (x *Entry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Entry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Entry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Entry) GetOwner() uint32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *Entry) GetGroup() uint32 {
	if x != nil {
		return x.Group
	}
	return 0
}

func (x *Entry) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *Entry) GetSourceHost() string {
	if x != nil {
		return x.SourceHost
	}
	return ""
}

var File_api_catalog_proto protoreflect.FileDescriptor

const file_api_catalog_proto_rawDesc = "" +
	"\n" +
	"\x11api/catalog.proto\x12\x0ecatalogservice\"\xb4\x01\n" +
	"\x10FileVersionEntry\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\fR\bmetadata\x12\x14\n" +
	"\x05ctime\x18\x04 \x01(\x03R\x05ctime\x12\x1b\n" +
	"\tstore_seq\x18\x05 \x01(\x03R\bstoreSeq\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"I\n" +
	"\vSyncRequest\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .catalogservice.FileVersionEntryR\aentries\"\x0e\n" +
	"\fSyncResponse\"\xab\x01\n" +
	"\x12ListEntriesRequest\x12\x1d\n" +
	"\n" +
	"store_host\x18\x01 \x01(\tR\tstoreHost\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12%\n" +
	"\x0estarting_after\x18\x04 \x01(\x03R\rstartingAfter\x12\x1f\n" +
	"\vsource_host\x18\x05 \x01(\tR\n" +
	"sourceHost\"a\n" +
	"\x13ListEntriesResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.catalogservice.EntryR\aentries\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xef\x02\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"store_host\x18\x02 \x01(\tR\tstoreHost\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tobject_id\x18\x04 \x01(\tR\bobjectId\x12\x14\n" +
	"\x05ctime\x18\x05 \x01(\x03R\x05ctime\x12(\n" +
	"\x10store_created_at\x18\x06 \x01(\x03R\x0estoreCreatedAt\x12\x1f\n" +
	"\vreceived_at\x18\a \x01(\x03R\n" +
	"receivedAt\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\t \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\n" +
	" \x01(\tR\x04mode\x12\x14\n" +
	"\x05owner\x18\v \x01(\rR\x05owner\x12\x14\n" +
	"\x05group\x18\f \x01(\rR\x05group\x12\x19\n" +
	"\bmod_time\x18\r \x01(\x03R\amodTime\x12\x1f\n" +
	"\vsource_host\x18\x0e \x01(\tR\n" +
	"sourceHost2\xb7\x01\n" +
	"\x0eCatalogService\x12M\n" +
	"\x10SyncFileVersions\x12\x1b.catalogservice.SyncRequest\x1a\x1c.catalogservice.SyncResponse\x12V\n" +
	"\vListEntries\x12\".catalogservice.ListEntriesRequest\x1a#.catalogservice.ListEntriesResponseB\tZ\a./protob\x06proto3"

var (
	file_api_catalog_proto_rawDescOnce sync.Once
	file_api_catalog_proto_rawDescData []byte
)

func file_api_catalog_proto_rawDescGZIP() []byte {
	file_api_catalog_proto_rawDescOnce.Do(func() {
		file_api_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_catalog_proto_rawDesc), len(file_api_catalog_proto_rawDesc)))
	})
	return file_api_catalog_proto_rawDescData
}

var file_api_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_catalog_proto_goTypes = []any{
	(*FileVersionEntry)(nil),    // 0: catalogservice.FileVersionEntry
	(*SyncRequest)(nil),         // 1: catalogservice.SyncRequest
	(*SyncResponse)(nil),        // 2: catalogservice.SyncResponse
	(*ListEntriesRequest)(nil),  // 3: catalogservice.ListEntriesRequest
	(*ListEntriesResponse)(nil), // 4: catalogservice.ListEntriesResponse
	(*Entry)(nil),               // 5: catalogservice.Entry
}
var file_api_catalog_proto_depIdxs = []int32{
	0, // 0: catalogservice.SyncRequest.entries:type_name -> catalogservice.FileVersionEntry
	5, // 1: catalogservice.ListEntriesResponse.entries:type_name -> catalogservice.Entry
	1, // 2: catalogservice.CatalogService.SyncFileVersions:input_type -> catalogservice.SyncRequest
	3, // 3: catalogservice.CatalogService.ListEntries:input_type -> catalogservice.ListEntriesRequest
	2, // 4: catalogservice.CatalogService.SyncFileVersions:output_type -> catalogservice.SyncResponse
	4, // 5: catalogservice.CatalogService.ListEntries:output_type -> catalogservice.ListEntriesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_catalog_proto_init() }
func file_api_catalog_proto_init() {
	if File_api_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_catalog_proto_rawDesc), len(file_api_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_catalog_proto_goTypes,
		DependencyIndexes: file_api_catalog_proto_depIdxs,
		MessageInfos:      file_api_catalog_proto_msgTypes,
	}.Build()
	File_api_catalog_proto = out.File
	file_api_catalog_proto_goTypes = nil
	file_api_catalog_proto_depIdxs = nil
}
