// src/api/clientmanageradmin.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/clientmanageradmin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientManagerAdminService_AddClient_FullMethodName         = "/clientmanageradminservice.ClientManagerAdminService/AddClient"
	ClientManagerAdminService_ReEnrollClient_FullMethodName    = "/clientmanageradminservice.ClientManagerAdminService/ReEnrollClient"
	ClientManagerAdminService_RevokeClient_FullMethodName      = "/clientmanageradminservice.ClientManagerAdminService/RevokeClient"
	ClientManagerAdminService_UnrevokeClient_FullMethodName    = "/clientmanageradminservice.ClientManagerAdminService/UnrevokeClient"
	ClientManagerAdminService_UpdateDescription_FullMethodName = "/clientmanageradminservice.ClientManagerAdminService/UpdateDescription"
	ClientManagerAdminService_UpdateAttributes_FullMethodName  = "/clientmanageradminservice.ClientManagerAdminService/UpdateAttributes"
	ClientManagerAdminService_UpdateSANs_FullMethodName        = "/clientmanageradminservice.ClientManagerAdminService/UpdateSANs"
)

// ClientManagerAdminServiceClient is the client API for ClientManagerAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientManagerAdminService holds the CA provisioner password directly
// (CA-admin-equivalent access) -- deliberately isolated from
// clientmanager-api's general-purpose, password-free read surface. See
// docs/superpowers/specs/2026-07-19-clientmanager-admin-api-design.md.
type ClientManagerAdminServiceClient interface {
	AddClient(ctx context.Context, in *AddClientRequest, opts ...grpc.CallOption) (*AddClientResponse, error)
	ReEnrollClient(ctx context.Context, in *ReEnrollClientRequest, opts ...grpc.CallOption) (*ReEnrollClientResponse, error)
	RevokeClient(ctx context.Context, in *RevokeClientRequest, opts ...grpc.CallOption) (*Client, error)
	UnrevokeClient(ctx context.Context, in *UnrevokeClientRequest, opts ...grpc.CallOption) (*Client, error)
	UpdateDescription(ctx context.Context, in *UpdateClientKVRequest, opts ...grpc.CallOption) (*Client, error)
	UpdateAttributes(ctx context.Context, in *UpdateClientKVRequest, opts ...grpc.CallOption) (*Client, error)
	UpdateSANs(ctx context.Context, in *UpdateClientSANsRequest, opts ...grpc.CallOption) (*Client, error)
}

type clientManagerAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientManagerAdminServiceClient(cc grpc.ClientConnInterface) ClientManagerAdminServiceClient {
	return &clientManagerAdminServiceClient{cc}
}

func (c *clientManagerAdminServiceClient) AddClient(ctx context.Context, in *AddClientRequest, opts ...grpc.CallOption) (*AddClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddClientResponse)
	err := c.cc.Invoke(ctx, ClientManagerAdminService_AddClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientManagerAdminServiceClient) ReEnrollClient(ctx context.Context, in *ReEnrollClientRequest, opts ...grpc.CallOption) (*ReEnrollClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReEnrollClientResponse)
	err := c.cc.Invoke(ctx, ClientManagerAdminService_ReEnrollClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientManagerAdminServiceClient) RevokeClient(ctx context.Context, in *RevokeClientRequest, opts ...grpc.CallOption) (*Client, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Client)
	err := c.cc.Invoke(ctx, ClientManagerAdminService_RevokeClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientManagerAdminServiceClient) UnrevokeClient(ctx context.Context, in *UnrevokeClientRequest, opts ...grpc.CallOption) (*Client, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Client)
	err := c.cc.Invoke(ctx, ClientManagerAdminService_UnrevokeClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientManagerAdminServiceClient) UpdateDescription(ctx context.Context, in *UpdateClientKVRequest, opts ...grpc.CallOption) (*Client, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Client)
	err := c.cc.Invoke(ctx, ClientManagerAdminService_UpdateDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientManagerAdminServiceClient) UpdateAttributes(ctx context.Context, in *UpdateClientKVRequest, opts ...grpc.CallOption) (*Client, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Client)
	err := c.cc.Invoke(ctx, ClientManagerAdminService_UpdateAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientManagerAdminServiceClient) UpdateSANs(ctx context.Context, in *UpdateClientSANsRequest, opts ...grpc.CallOption) (*Client, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Client)
	err := c.cc.Invoke(ctx, ClientManagerAdminService_UpdateSANs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientManagerAdminServiceServer is the server API for ClientManagerAdminService service.
// All implementations must embed UnimplementedClientManagerAdminServiceServer
// for forward compatibility.
//
// ClientManagerAdminService holds the CA provisioner password directly
// (CA-admin-equivalent access) -- deliberately isolated from
// clientmanager-api's general-purpose, password-free read surface. See
// docs/superpowers/specs/2026-07-19-clientmanager-admin-api-design.md.
type ClientManagerAdminServiceServer interface {
	AddClient(context.Context, *AddClientRequest) (*AddClientResponse, error)
	ReEnrollClient(context.Context, *ReEnrollClientRequest) (*ReEnrollClientResponse, error)
	RevokeClient(context.Context, *RevokeClientRequest) (*Client, error)
	UnrevokeClient(context.Context, *UnrevokeClientRequest) (*Client, error)
	UpdateDescription(context.Context, *UpdateClientKVRequest) (*Client, error)
	UpdateAttributes(context.Context, *UpdateClientKVRequest) (*Client, error)
	UpdateSANs(context.Context, *UpdateClientSANsRequest) (*Client, error)
	mustEmbedUnimplementedClientManagerAdminServiceServer()
}

// UnimplementedClientManagerAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientManagerAdminServiceServer struct{}

func (UnimplementedClientManagerAdminServiceServer) AddClient(context.Context, *AddClientRequest) (*AddClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddClient not implemented")
}
func (UnimplementedClientManagerAdminServiceServer) ReEnrollClient(context.Context, *ReEnrollClientRequest) (*ReEnrollClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReEnrollClient not implemented")
}
func (UnimplementedClientManagerAdminServiceServer) RevokeClient(context.Context, *RevokeClientRequest) (*Client, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeClient not implemented")
}
func (UnimplementedClientManagerAdminServiceServer) UnrevokeClient(context.Context, *UnrevokeClientRequest) (*Client, error) {
	return nil, status.Error(codes.Unimplemented, "method UnrevokeClient not implemented")
}
func (UnimplementedClientManagerAdminServiceServer) UpdateDescription(context.Context, *UpdateClientKVRequest) (*Client, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDescription not implemented")
}
func (UnimplementedClientManagerAdminServiceServer) UpdateAttributes(context.Context, *UpdateClientKVRequest) (*Client, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAttributes not implemented")
}
func (UnimplementedClientManagerAdminServiceServer) UpdateSANs(context.Context, *UpdateClientSANsRequest) (*Client, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSANs not implemented")
}
func (UnimplementedClientManagerAdminServiceServer) mustEmbedUnimplementedClientManagerAdminServiceServer() {
}
func (UnimplementedClientManagerAdminServiceServer) testEmbeddedByValue() {}

// UnsafeClientManagerAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientManagerAdminServiceServer will
// result in compilation errors.
type UnsafeClientManagerAdminServiceServer interface {
	mustEmbedUnimplementedClientManagerAdminServiceServer()
}

func RegisterClientManagerAdminServiceServer(s grpc.ServiceRegistrar, srv ClientManagerAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedClientManagerAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientManagerAdminService_ServiceDesc, srv)
}

func _ClientManagerAdminService_AddClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientManagerAdminServiceServer).AddClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientManagerAdminService_AddClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientManagerAdminServiceServer).AddClient(ctx, req.(*AddClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientManagerAdminService_ReEnrollClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReEnrollClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientManagerAdminServiceServer).ReEnrollClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientManagerAdminService_ReEnrollClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientManagerAdminServiceServer).ReEnrollClient(ctx, req.(*ReEnrollClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientManagerAdminService_RevokeClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientManagerAdminServiceServer).RevokeClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientManagerAdminService_RevokeClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientManagerAdminServiceServer).RevokeClient(ctx, req.(*RevokeClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientManagerAdminService_UnrevokeClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnrevokeClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientManagerAdminServiceServer).UnrevokeClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientManagerAdminService_UnrevokeClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientManagerAdminServiceServer).UnrevokeClient(ctx, req.(*UnrevokeClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientManagerAdminService_UpdateDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientManagerAdminServiceServer).UpdateDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientManagerAdminService_UpdateDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientManagerAdminServiceServer).UpdateDescription(ctx, req.(*UpdateClientKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientManagerAdminService_UpdateAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientManagerAdminServiceServer).UpdateAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientManagerAdminService_UpdateAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientManagerAdminServiceServer).UpdateAttributes(ctx, req.(*UpdateClientKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientManagerAdminService_UpdateSANs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClientSANsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientManagerAdminServiceServer).UpdateSANs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientManagerAdminService_UpdateSANs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientManagerAdminServiceServer).UpdateSANs(ctx, req.(*UpdateClientSANsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientManagerAdminService_ServiceDesc is the grpc.ServiceDesc for ClientManagerAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientManagerAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clientmanageradminservice.ClientManagerAdminService",
	HandlerType: (*ClientManagerAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddClient",
			Handler:    _ClientManagerAdminService_AddClient_Handler,
		},
		{
			MethodName: "ReEnrollClient",
			Handler:    _ClientManagerAdminService_ReEnrollClient_Handler,
		},
		{
			MethodName: "RevokeClient",
			Handler:    _ClientManagerAdminService_RevokeClient_Handler,
		},
		{
			MethodName: "UnrevokeClient",
			Handler:    _ClientManagerAdminService_UnrevokeClient_Handler,
		},
		{
			MethodName: "UpdateDescription",
			Handler:    _ClientManagerAdminService_UpdateDescription_Handler,
		},
		{
			MethodName: "UpdateAttributes",
			Handler:    _ClientManagerAdminService_UpdateAttributes_Handler,
		},
		{
			MethodName: "UpdateSANs",
			Handler:    _ClientManagerAdminService_UpdateSANs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/clientmanageradmin.proto",
}
