// src/api/clientmanageradmin.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/clientmanageradmin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Sans          []string               `protobuf:"bytes,2,rep,name=sans,proto3" json:"sans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClientRequest) Reset() {
	*x = AddClientRequest{}
	mi := &file_api_clientmanageradmin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClientRequest) ProtoMessage() {}

func (x *AddClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanageradmin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClientRequest.ProtoReflect.Descriptor instead.
func (*AddClientRequest) Descriptor() ([]byte, []int) {
	return file_api_clientmanageradmin_proto_rawDescGZIP(), []int{0}
}

func (x *AddClientRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AddClientRequest) GetSans() []string {
	if x != nil {
		return x.Sans
	}
	return nil
}

type AddClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClientResponse) Reset() {
	*x = AddClientResponse{}
	mi := &file_api_clientmanageradmin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClientResponse) ProtoMessage() {}

func (x *AddClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanageradmin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClientResponse.ProtoReflect.Descriptor instead.
func (*AddClientResponse) Descriptor() ([]byte, []int) {
	return file_api_clientmanageradmin_proto_rawDescGZIP(), []int{1}
}

func (x *AddClientResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ReEnrollClientRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Hostname string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Empty means keep the hostname's currently stored SANs.
	Sans          []string `protobuf:"bytes,2,rep,name=sans,proto3" json:"sans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEnrollClientRequest) Reset() {
	*x = ReEnrollClientRequest{}
	mi := &file_api_clientmanageradmin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEnrollClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEnrollClientRequest) ProtoMessage() {}

func (x *ReEnrollClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanageradmin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEnrollClientRequest.ProtoReflect.Descriptor instead.
func (*ReEnrollClientRequest) Descriptor() ([]byte, []int) {
	return file_api_clientmanageradmin_proto_rawDescGZIP(), []int{2}
}

func (x *ReEnrollClientRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ReEnrollClientRequest) GetSans() []string {
	if x != nil {
		return x.Sans
	}
	return nil
}

type ReEnrollClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEnrollClientResponse) Reset() {
	*x = ReEnrollClientResponse{}
	mi := &file_api_clientmanageradmin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEnrollClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEnrollClientResponse) ProtoMessage() {}

func (x *ReEnrollClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanageradmin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEnrollClientResponse.ProtoReflect.Descriptor instead.
func (*ReEnrollClientResponse) Descriptor() ([]byte, []int) {
	return file_api_clientmanageradmin_proto_rawDescGZIP(), []int{3}
}

func (x *ReEnrollClientResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RevokeClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeClientRequest) Reset() {
	*x = RevokeClientRequest{}
	mi := &file_api_clientmanageradmin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeClientRequest) ProtoMessage() {}

func (x *RevokeClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanageradmin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeClientRequest.ProtoReflect.Descriptor instead.
func (*RevokeClientRequest) Descriptor() ([]byte, []int) {
	return file_api_clientmanageradmin_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeClientRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type UnrevokeClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnrevokeClientRequest) Reset() {
	*x = UnrevokeClientRequest{}
	mi := &file_api_clientmanageradmin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnrevokeClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnrevokeClientRequest) ProtoMessage() {}

func (x *UnrevokeClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanageradmin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnrevokeClientRequest.ProtoReflect.Descriptor instead.
func (*UnrevokeClientRequest) Descriptor() ([]byte, []int) {
	return file_api_clientmanageradmin_proto_rawDescGZIP(), []int{5}
}

func (x *UnrevokeClientRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type UpdateClientKVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Set           map[string]string      `protobuf:"bytes,2,rep,name=set,proto3" json:"set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Unset         []string               `protobuf:"bytes,3,rep,name=unset,proto3" json:"unset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientKVRequest) Reset() {
	*x = UpdateClientKVRequest{}
	mi := &file_api_clientmanageradmin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientKVRequest) ProtoMessage() {}

func (x *UpdateClientKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanageradmin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientKVRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientKVRequest) Descriptor() ([]byte, []int) {
	return file_api_clientmanageradmin_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateClientKVRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *UpdateClientKVRequest) GetSet() map[string]string {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *UpdateClientKVRequest) GetUnset() []string {
	if x != nil {
		return x.Unset
	}
	return nil
}

type UpdateClientSANsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Add           []string               `protobuf:"bytes,2,rep,name=add,proto3" json:"add,omitempty"`
	Remove        []string               `protobuf:"bytes,3,rep,name=remove,proto3" json:"remove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientSANsRequest) Reset() {
	*x = UpdateClientSANsRequest{}
	mi := &file_api_clientmanageradmin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientSANsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientSANsRequest) ProtoMessage() {}

func (x *UpdateClientSANsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanageradmin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientSANsRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientSANsRequest) Descriptor() ([]byte, []int) {
	return file_api_clientmanageradmin_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateClientSANsRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *UpdateClientSANsRequest) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *UpdateClientSANsRequest) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

var File_api_clientmanageradmin_proto protoreflect.FileDescriptor

const file_api_clientmanageradmin_proto_rawDesc = "" +
	"\n" +
	"\x1capi/clientmanageradmin.proto\x12\x19clientmanageradminservice\x1a\x17api/clientmanager.proto\"B\n" +
	"\x10AddClientRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04sans\x18\x02 \x03(\tR\x04sans\")\n" +
	"\x11AddClientResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"G\n" +
	"\x15ReEnrollClientRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04sans\x18\x02 \x03(\tR\x04sans\".\n" +
	"\x16ReEnrollClientResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"1\n" +
	"\x13RevokeClientRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"3\n" +
	"\x15UnrevokeClientRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\xce\x01\n" +
	"\x15UpdateClientKVRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12K\n" +
	"\x03set\x18\x02 \x03(\v29.clientmanageradminservice.UpdateClientKVRequest.SetEntryR\x03set\x12\x14\n" +
	"\x05unset\x18\x03 \x03(\tR\x05unset\x1a6\n" +
	"\bSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x17UpdateClientSANsRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x10\n" +
	"\x03add\x18\x02 \x03(\tR\x03add\x12\x16\n" +
	"\x06remove\x18\x03 \x03(\tR\x06remove2\xf2\x05\n" +
	"\x19ClientManagerAdminService\x12f\n" +
	"\tAddClient\x12+.clientmanageradminservice.AddClientRequest\x1a,.clientmanageradminservice.AddClientResponse\x12u\n" +
	"\x0eReEnrollClient\x120.clientmanageradminservice.ReEnrollClientRequest\x1a1.clientmanageradminservice.ReEnrollClientResponse\x12_\n" +
	"\fRevokeClient\x12..clientmanageradminservice.RevokeClientRequest\x1a\x1f.clientmanagerapiservice.Client\x12c\n" +
	"\x0eUnrevokeClient\x120.clientmanageradminservice.UnrevokeClientRequest\x1a\x1f.clientmanagerapiservice.Client\x12f\n" +
	"\x11UpdateDescription\x120.clientmanageradminservice.UpdateClientKVRequest\x1a\x1f.clientmanagerapiservice.Client\x12e\n" +
	"\x10UpdateAttributes\x120.clientmanageradminservice.UpdateClientKVRequest\x1a\x1f.clientmanagerapiservice.Client\x12a\n" +
	"\n" +
	"UpdateSANs\x122.clientmanageradminservice.UpdateClientSANsRequest\x1a\x1f.clientmanagerapiservice.ClientB\tZ\a./protob\x06proto3"

var (
	file_api_clientmanageradmin_proto_rawDescOnce sync.Once
	file_api_clientmanageradmin_proto_rawDescData []byte
)

func file_api_clientmanageradmin_proto_rawDescGZIP() []byte {
	file_api_clientmanageradmin_proto_rawDescOnce.Do(func() {
		file_api_clientmanageradmin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_clientmanageradmin_proto_rawDesc), len(file_api_clientmanageradmin_proto_rawDesc)))
	})
	return file_api_clientmanageradmin_proto_rawDescData
}

var file_api_clientmanageradmin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_clientmanageradmin_proto_goTypes = []any{
	(*AddClientRequest)(nil),        // 0: clientmanageradminservice.AddClientRequest
	(*AddClientResponse)(nil),       // 1: clientmanageradminservice.AddClientResponse
	(*ReEnrollClientRequest)(nil),   // 2: clientmanageradminservice.ReEnrollClientRequest
	(*ReEnrollClientResponse)(nil),  // 3: clientmanageradminservice.ReEnrollClientResponse
	(*RevokeClientRequest)(nil),     // 4: clientmanageradminservice.RevokeClientRequest
	(*UnrevokeClientRequest)(nil),   // 5: clientmanageradminservice.UnrevokeClientRequest
	(*UpdateClientKVRequest)(nil),   // 6: clientmanageradminservice.UpdateClientKVRequest
	(*UpdateClientSANsRequest)(nil), // 7: clientmanageradminservice.UpdateClientSANsRequest
	nil,                             // 8: clientmanageradminservice.UpdateClientKVRequest.SetEntry
	(*Client)(nil),                  // 9: clientmanagerapiservice.Client
}
var file_api_clientmanageradmin_proto_depIdxs = []int32{
	8, // 0: clientmanageradminservice.UpdateClientKVRequest.set:type_name -> clientmanageradminservice.UpdateClientKVRequest.SetEntry
	0, // 1: clientmanageradminservice.ClientManagerAdminService.AddClient:input_type -> clientmanageradminservice.AddClientRequest
	2, // 2: clientmanageradminservice.ClientManagerAdminService.ReEnrollClient:input_type -> clientmanageradminservice.ReEnrollClientRequest
	4, // 3: clientmanageradminservice.ClientManagerAdminService.RevokeClient:input_type -> clientmanageradminservice.RevokeClientRequest
	5, // 4: clientmanageradminservice.ClientManagerAdminService.UnrevokeClient:input_type -> clientmanageradminservice.UnrevokeClientRequest
	6, // 5: clientmanageradminservice.ClientManagerAdminService.UpdateDescription:input_type -> clientmanageradminservice.UpdateClientKVRequest
	6, // 6: clientmanageradminservice.ClientManagerAdminService.UpdateAttributes:input_type -> clientmanageradminservice.UpdateClientKVRequest
	7, // 7: clientmanageradminservice.ClientManagerAdminService.UpdateSANs:input_type -> clientmanageradminservice.UpdateClientSANsRequest
	1, // 8: clientmanageradminservice.ClientManagerAdminService.AddClient:output_type -> clientmanageradminservice.AddClientResponse
	3, // 9: clientmanageradminservice.ClientManagerAdminService.ReEnrollClient:output_type -> clientmanageradminservice.ReEnrollClientResponse
	9, // 10: clientmanageradminservice.ClientManagerAdminService.RevokeClient:output_type -> clientmanagerapiservice.Client
	9, // 11: clientmanageradminservice.ClientManagerAdminService.UnrevokeClient:output_type -> clientmanagerapiservice.Client
	9, // 12: clientmanageradminservice.ClientManagerAdminService.UpdateDescription:output_type -> clientmanagerapiservice.Client
	9, // 13: clientmanageradminservice.ClientManagerAdminService.UpdateAttributes:output_type -> clientmanagerapiservice.Client
	9, // 14: clientmanageradminservice.ClientManagerAdminService.UpdateSANs:output_type -> clientmanagerapiservice.Client
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_clientmanageradmin_proto_init() }
func file_api_clientmanageradmin_proto_init() {
	if File_api_clientmanageradmin_proto != nil {
		return
	}
	file_api_clientmanager_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_clientmanageradmin_proto_rawDesc), len(file_api_clientmanageradmin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_clientmanageradmin_proto_goTypes,
		DependencyIndexes: file_api_clientmanageradmin_proto_depIdxs,
		MessageInfos:      file_api_clientmanageradmin_proto_msgTypes,
	}.Build()
	File_api_clientmanageradmin_proto = out.File
	file_api_clientmanageradmin_proto_goTypes = nil
	file_api_clientmanageradmin_proto_depIdxs = nil
}
