// src/api/clientmanager.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/clientmanager.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientManagerService_ListClients_FullMethodName = "/clientmanagerapiservice.ClientManagerService/ListClients"
	ClientManagerService_GetClient_FullMethodName   = "/clientmanagerapiservice.ClientManagerService/GetClient"
)

// ClientManagerServiceClient is the client API for ClientManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientManagerService is clientmanager-api's sole RPC surface: read-only
// access to the same clientmanager.sqlite file client-manager's CLI and
// issuer already share (see docs/superpowers/specs/2026-07-04-client-manager-phase2-design.md
// and docs/superpowers/specs/2026-07-14-api-server-design.md). clientmanager-api
// never writes -- client-manager (the CLI) and issuer remain the only writers.
type ClientManagerServiceClient interface {
	ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error)
	GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*Client, error)
}

type clientManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientManagerServiceClient(cc grpc.ClientConnInterface) ClientManagerServiceClient {
	return &clientManagerServiceClient{cc}
}

func (c *clientManagerServiceClient) ListClients(ctx context.Context, in *ListClientsRequest, opts ...grpc.CallOption) (*ListClientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClientsResponse)
	err := c.cc.Invoke(ctx, ClientManagerService_ListClients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientManagerServiceClient) GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*Client, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Client)
	err := c.cc.Invoke(ctx, ClientManagerService_GetClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientManagerServiceServer is the server API for ClientManagerService service.
// All implementations must embed UnimplementedClientManagerServiceServer
// for forward compatibility.
//
// ClientManagerService is clientmanager-api's sole RPC surface: read-only
// access to the same clientmanager.sqlite file client-manager's CLI and
// issuer already share (see docs/superpowers/specs/2026-07-04-client-manager-phase2-design.md
// and docs/superpowers/specs/2026-07-14-api-server-design.md). clientmanager-api
// never writes -- client-manager (the CLI) and issuer remain the only writers.
type ClientManagerServiceServer interface {
	ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error)
	GetClient(context.Context, *GetClientRequest) (*Client, error)
	mustEmbedUnimplementedClientManagerServiceServer()
}

// UnimplementedClientManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientManagerServiceServer struct{}

func (UnimplementedClientManagerServiceServer) ListClients(context.Context, *ListClientsRequest) (*ListClientsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClients not implemented")
}
func (UnimplementedClientManagerServiceServer) GetClient(context.Context, *GetClientRequest) (*Client, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClient not implemented")
}
func (UnimplementedClientManagerServiceServer) mustEmbedUnimplementedClientManagerServiceServer() {}
func (UnimplementedClientManagerServiceServer) testEmbeddedByValue()                              {}

// UnsafeClientManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientManagerServiceServer will
// result in compilation errors.
type UnsafeClientManagerServiceServer interface {
	mustEmbedUnimplementedClientManagerServiceServer()
}

func RegisterClientManagerServiceServer(s grpc.ServiceRegistrar, srv ClientManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedClientManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientManagerService_ServiceDesc, srv)
}

func _ClientManagerService_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientManagerServiceServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientManagerService_ListClients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientManagerServiceServer).ListClients(ctx, req.(*ListClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientManagerService_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientManagerServiceServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientManagerService_GetClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientManagerServiceServer).GetClient(ctx, req.(*GetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientManagerService_ServiceDesc is the grpc.ServiceDesc for ClientManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clientmanagerapiservice.ClientManagerService",
	HandlerType: (*ClientManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListClients",
			Handler:    _ClientManagerService_ListClients_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _ClientManagerService_GetClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/clientmanager.proto",
}
