// src/api/clientmanager.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/clientmanager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Revoked       bool                   `protobuf:"varint,2,opt,name=revoked,proto3" json:"revoked,omitempty"`
	RevokedAt     int64                  `protobuf:"varint,3,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`      // unix seconds, 0 if never revoked
	LastSeenAt    int64                  `protobuf:"varint,4,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"` // unix seconds, 0 if never seen
	Sans          []string               `protobuf:"bytes,5,rep,name=sans,proto3" json:"sans,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Descriptions  map[string]string      `protobuf:"bytes,7,rep,name=descriptions,proto3" json:"descriptions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_api_clientmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_api_clientmanager_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Client) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *Client) GetRevokedAt() int64 {
	if x != nil {
		return x.RevokedAt
	}
	return 0
}

func (x *Client) GetLastSeenAt() int64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

func (x *Client) GetSans() []string {
	if x != nil {
		return x.Sans
	}
	return nil
}

func (x *Client) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Client) GetDescriptions() map[string]string {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

type ListClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsRequest) Reset() {
	*x = ListClientsRequest{}
	mi := &file_api_clientmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsRequest) ProtoMessage() {}

func (x *ListClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsRequest.ProtoReflect.Descriptor instead.
func (*ListClientsRequest) Descriptor() ([]byte, []int) {
	return file_api_clientmanager_proto_rawDescGZIP(), []int{1}
}

type ListClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*Client              `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClientsResponse) Reset() {
	*x = ListClientsResponse{}
	mi := &file_api_clientmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClientsResponse) ProtoMessage() {}

func (x *ListClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClientsResponse.ProtoReflect.Descriptor instead.
func (*ListClientsResponse) Descriptor() ([]byte, []int) {
	return file_api_clientmanager_proto_rawDescGZIP(), []int{2}
}

func (x *ListClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

type GetClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
	mi := &file_api_clientmanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_clientmanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRequest.ProtoReflect.Descriptor instead.
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return file_api_clientmanager_proto_rawDescGZIP(), []int{3}
}

func (x *GetClientRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

var File_api_clientmanager_proto protoreflect.FileDescriptor

const file_api_clientmanager_proto_rawDesc = "" +
	"\n" +
	"\x17api/clientmanager.proto\x12\x17clientmanagerapiservice\"\xbb\x03\n" +
	"\x06Client\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x18\n" +
	"\arevoked\x18\x02 \x01(\bR\arevoked\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x03 \x01(\x03R\trevokedAt\x12 \n" +
	"\flast_seen_at\x18\x04 \x01(\x03R\n" +
	"lastSeenAt\x12\x12\n" +
	"\x04sans\x18\x05 \x03(\tR\x04sans\x12O\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2/.clientmanagerapiservice.Client.AttributesEntryR\n" +
	"attributes\x12U\n" +
	"\fdescriptions\x18\a \x03(\v21.clientmanagerapiservice.Client.DescriptionsEntryR\fdescriptions\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11DescriptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12ListClientsRequest\"P\n" +
	"\x13ListClientsResponse\x129\n" +
	"\aclients\x18\x01 \x03(\v2\x1f.clientmanagerapiservice.ClientR\aclients\".\n" +
	"\x10GetClientRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname2\xd9\x01\n" +
	"\x14ClientManagerService\x12h\n" +
	"\vListClients\x12+.clientmanagerapiservice.ListClientsRequest\x1a,.clientmanagerapiservice.ListClientsResponse\x12W\n" +
	"\tGetClient\x12).clientmanagerapiservice.GetClientRequest\x1a\x1f.clientmanagerapiservice.ClientB\tZ\a./protob\x06proto3"

var (
	file_api_clientmanager_proto_rawDescOnce sync.Once
	file_api_clientmanager_proto_rawDescData []byte
)

func file_api_clientmanager_proto_rawDescGZIP() []byte {
	file_api_clientmanager_proto_rawDescOnce.Do(func() {
		file_api_clientmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_clientmanager_proto_rawDesc), len(file_api_clientmanager_proto_rawDesc)))
	})
	return file_api_clientmanager_proto_rawDescData
}

var file_api_clientmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_clientmanager_proto_goTypes = []any{
	(*Client)(nil),              // 0: clientmanagerapiservice.Client
	(*ListClientsRequest)(nil),  // 1: clientmanagerapiservice.ListClientsRequest
	(*ListClientsResponse)(nil), // 2: clientmanagerapiservice.ListClientsResponse
	(*GetClientRequest)(nil),    // 3: clientmanagerapiservice.GetClientRequest
	nil,                         // 4: clientmanagerapiservice.Client.AttributesEntry
	nil,                         // 5: clientmanagerapiservice.Client.DescriptionsEntry
}
var file_api_clientmanager_proto_depIdxs = []int32{
	4, // 0: clientmanagerapiservice.Client.attributes:type_name -> clientmanagerapiservice.Client.AttributesEntry
	5, // 1: clientmanagerapiservice.Client.descriptions:type_name -> clientmanagerapiservice.Client.DescriptionsEntry
	0, // 2: clientmanagerapiservice.ListClientsResponse.clients:type_name -> clientmanagerapiservice.Client
	1, // 3: clientmanagerapiservice.ClientManagerService.ListClients:input_type -> clientmanagerapiservice.ListClientsRequest
	3, // 4: clientmanagerapiservice.ClientManagerService.GetClient:input_type -> clientmanagerapiservice.GetClientRequest
	2, // 5: clientmanagerapiservice.ClientManagerService.ListClients:output_type -> clientmanagerapiservice.ListClientsResponse
	0, // 6: clientmanagerapiservice.ClientManagerService.GetClient:output_type -> clientmanagerapiservice.Client
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_clientmanager_proto_init() }
func file_api_clientmanager_proto_init() {
	if File_api_clientmanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_clientmanager_proto_rawDesc), len(file_api_clientmanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_clientmanager_proto_goTypes,
		DependencyIndexes: file_api_clientmanager_proto_depIdxs,
		MessageInfos:      file_api_clientmanager_proto_msgTypes,
	}.Build()
	File_api_clientmanager_proto = out.File
	file_api_clientmanager_proto_goTypes = nil
	file_api_clientmanager_proto_depIdxs = nil
}
