// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/enrollment_broker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MintEnrollmentTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Sans          []string               `protobuf:"bytes,2,rep,name=sans,proto3" json:"sans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintEnrollmentTokenRequest) Reset() {
	*x = MintEnrollmentTokenRequest{}
	mi := &file_api_enrollment_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintEnrollmentTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintEnrollmentTokenRequest) ProtoMessage() {}

func (x *MintEnrollmentTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_enrollment_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintEnrollmentTokenRequest.ProtoReflect.Descriptor instead.
func (*MintEnrollmentTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_enrollment_broker_proto_rawDescGZIP(), []int{0}
}

func (x *MintEnrollmentTokenRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MintEnrollmentTokenRequest) GetSans() []string {
	if x != nil {
		return x.Sans
	}
	return nil
}

type MintEnrollmentTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintEnrollmentTokenResponse) Reset() {
	*x = MintEnrollmentTokenResponse{}
	mi := &file_api_enrollment_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintEnrollmentTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintEnrollmentTokenResponse) ProtoMessage() {}

func (x *MintEnrollmentTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_enrollment_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintEnrollmentTokenResponse.ProtoReflect.Descriptor instead.
func (*MintEnrollmentTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_enrollment_broker_proto_rawDescGZIP(), []int{1}
}

func (x *MintEnrollmentTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_enrollment_broker_proto protoreflect.FileDescriptor

const file_api_enrollment_broker_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/enrollment_broker.proto\x12\x10enrollmentbroker\"L\n" +
	"\x1aMintEnrollmentTokenRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04sans\x18\x02 \x03(\tR\x04sans\"3\n" +
	"\x1bMintEnrollmentTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\x8d\x01\n" +
	"\x17EnrollmentBrokerService\x12r\n" +
	"\x13MintEnrollmentToken\x12,.enrollmentbroker.MintEnrollmentTokenRequest\x1a-.enrollmentbroker.MintEnrollmentTokenResponseB\tZ\a./protob\x06proto3"

var (
	file_api_enrollment_broker_proto_rawDescOnce sync.Once
	file_api_enrollment_broker_proto_rawDescData []byte
)

func file_api_enrollment_broker_proto_rawDescGZIP() []byte {
	file_api_enrollment_broker_proto_rawDescOnce.Do(func() {
		file_api_enrollment_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_enrollment_broker_proto_rawDesc), len(file_api_enrollment_broker_proto_rawDesc)))
	})
	return file_api_enrollment_broker_proto_rawDescData
}

var file_api_enrollment_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_enrollment_broker_proto_goTypes = []any{
	(*MintEnrollmentTokenRequest)(nil),  // 0: enrollmentbroker.MintEnrollmentTokenRequest
	(*MintEnrollmentTokenResponse)(nil), // 1: enrollmentbroker.MintEnrollmentTokenResponse
}
var file_api_enrollment_broker_proto_depIdxs = []int32{
	0, // 0: enrollmentbroker.EnrollmentBrokerService.MintEnrollmentToken:input_type -> enrollmentbroker.MintEnrollmentTokenRequest
	1, // 1: enrollmentbroker.EnrollmentBrokerService.MintEnrollmentToken:output_type -> enrollmentbroker.MintEnrollmentTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_enrollment_broker_proto_init() }
func file_api_enrollment_broker_proto_init() {
	if File_api_enrollment_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_enrollment_broker_proto_rawDesc), len(file_api_enrollment_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_enrollment_broker_proto_goTypes,
		DependencyIndexes: file_api_enrollment_broker_proto_depIdxs,
		MessageInfos:      file_api_enrollment_broker_proto_msgTypes,
	}.Build()
	File_api_enrollment_broker_proto = out.File
	file_api_enrollment_broker_proto_goTypes = nil
	file_api_enrollment_broker_proto_depIdxs = nil
}
