// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/enrollment_broker.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnrollmentBrokerService_MintEnrollmentToken_FullMethodName = "/enrollmentbroker.EnrollmentBrokerService/MintEnrollmentToken"
)

// EnrollmentBrokerServiceClient is the client API for EnrollmentBrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EnrollmentBrokerService is certrequest serve's entire RPC surface: one
// method, mint an enrollment token, gated by an exact caller-hostname
// match against client_manager_host -- not the mesh's usual
// any-valid-cert-is-trusted posture, since this RPC is equivalent to
// CA-admin privilege.
type EnrollmentBrokerServiceClient interface {
	MintEnrollmentToken(ctx context.Context, in *MintEnrollmentTokenRequest, opts ...grpc.CallOption) (*MintEnrollmentTokenResponse, error)
}

type enrollmentBrokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentBrokerServiceClient(cc grpc.ClientConnInterface) EnrollmentBrokerServiceClient {
	return &enrollmentBrokerServiceClient{cc}
}

func (c *enrollmentBrokerServiceClient) MintEnrollmentToken(ctx context.Context, in *MintEnrollmentTokenRequest, opts ...grpc.CallOption) (*MintEnrollmentTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintEnrollmentTokenResponse)
	err := c.cc.Invoke(ctx, EnrollmentBrokerService_MintEnrollmentToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentBrokerServiceServer is the server API for EnrollmentBrokerService service.
// All implementations must embed UnimplementedEnrollmentBrokerServiceServer
// for forward compatibility.
//
// EnrollmentBrokerService is certrequest serve's entire RPC surface: one
// method, mint an enrollment token, gated by an exact caller-hostname
// match against client_manager_host -- not the mesh's usual
// any-valid-cert-is-trusted posture, since this RPC is equivalent to
// CA-admin privilege.
type EnrollmentBrokerServiceServer interface {
	MintEnrollmentToken(context.Context, *MintEnrollmentTokenRequest) (*MintEnrollmentTokenResponse, error)
	mustEmbedUnimplementedEnrollmentBrokerServiceServer()
}

// UnimplementedEnrollmentBrokerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrollmentBrokerServiceServer struct{}

func (UnimplementedEnrollmentBrokerServiceServer) MintEnrollmentToken(context.Context, *MintEnrollmentTokenRequest) (*MintEnrollmentTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintEnrollmentToken not implemented")
}
func (UnimplementedEnrollmentBrokerServiceServer) mustEmbedUnimplementedEnrollmentBrokerServiceServer() {
}
func (UnimplementedEnrollmentBrokerServiceServer) testEmbeddedByValue() {}

// UnsafeEnrollmentBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentBrokerServiceServer will
// result in compilation errors.
type UnsafeEnrollmentBrokerServiceServer interface {
	mustEmbedUnimplementedEnrollmentBrokerServiceServer()
}

func RegisterEnrollmentBrokerServiceServer(s grpc.ServiceRegistrar, srv EnrollmentBrokerServiceServer) {
	// If the following call panics, it indicates UnimplementedEnrollmentBrokerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnrollmentBrokerService_ServiceDesc, srv)
}

func _EnrollmentBrokerService_MintEnrollmentToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintEnrollmentTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentBrokerServiceServer).MintEnrollmentToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentBrokerService_MintEnrollmentToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentBrokerServiceServer).MintEnrollmentToken(ctx, req.(*MintEnrollmentTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrollmentBrokerService_ServiceDesc is the grpc.ServiceDesc for EnrollmentBrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrollmentBrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "enrollmentbroker.EnrollmentBrokerService",
	HandlerType: (*EnrollmentBrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintEnrollmentToken",
			Handler:    _EnrollmentBrokerService_MintEnrollmentToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/enrollment_broker.proto",
}
