// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/issuer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestOperatingCertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DER-encoded PKCS#10 certificate signing request. The caller's private
	// key never leaves the caller -- only the CSR crosses the wire.
	CsrDer        []byte `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOperatingCertRequest) Reset() {
	*x = RequestOperatingCertRequest{}
	mi := &file_api_issuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOperatingCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOperatingCertRequest) ProtoMessage() {}

func (x *RequestOperatingCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_issuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOperatingCertRequest.ProtoReflect.Descriptor instead.
func (*RequestOperatingCertRequest) Descriptor() ([]byte, []int) {
	return file_api_issuer_proto_rawDescGZIP(), []int{0}
}

func (x *RequestOperatingCertRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type RequestOperatingCertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full certificate chain (leaf + any intermediates), PEM-encoded,
	// concatenated in order -- ready to write directly to client.crt.
	CertChainPem  []byte `protobuf:"bytes,1,opt,name=cert_chain_pem,json=certChainPem,proto3" json:"cert_chain_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOperatingCertResponse) Reset() {
	*x = RequestOperatingCertResponse{}
	mi := &file_api_issuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOperatingCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOperatingCertResponse) ProtoMessage() {}

func (x *RequestOperatingCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_issuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOperatingCertResponse.ProtoReflect.Descriptor instead.
func (*RequestOperatingCertResponse) Descriptor() ([]byte, []int) {
	return file_api_issuer_proto_rawDescGZIP(), []int{1}
}

func (x *RequestOperatingCertResponse) GetCertChainPem() []byte {
	if x != nil {
		return x.CertChainPem
	}
	return nil
}

var File_api_issuer_proto protoreflect.FileDescriptor

const file_api_issuer_proto_rawDesc = "" +
	"\n" +
	"\x10api/issuer.proto\x12\rissuerservice\"6\n" +
	"\x1bRequestOperatingCertRequest\x12\x17\n" +
	"\acsr_der\x18\x01 \x01(\fR\x06csrDer\"D\n" +
	"\x1cRequestOperatingCertResponse\x12$\n" +
	"\x0ecert_chain_pem\x18\x01 \x01(\fR\fcertChainPem2\x80\x01\n" +
	"\rIssuerService\x12o\n" +
	"\x14RequestOperatingCert\x12*.issuerservice.RequestOperatingCertRequest\x1a+.issuerservice.RequestOperatingCertResponseB\tZ\a./protob\x06proto3"

var (
	file_api_issuer_proto_rawDescOnce sync.Once
	file_api_issuer_proto_rawDescData []byte
)

func file_api_issuer_proto_rawDescGZIP() []byte {
	file_api_issuer_proto_rawDescOnce.Do(func() {
		file_api_issuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_issuer_proto_rawDesc), len(file_api_issuer_proto_rawDesc)))
	})
	return file_api_issuer_proto_rawDescData
}

var file_api_issuer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_issuer_proto_goTypes = []any{
	(*RequestOperatingCertRequest)(nil),  // 0: issuerservice.RequestOperatingCertRequest
	(*RequestOperatingCertResponse)(nil), // 1: issuerservice.RequestOperatingCertResponse
}
var file_api_issuer_proto_depIdxs = []int32{
	0, // 0: issuerservice.IssuerService.RequestOperatingCert:input_type -> issuerservice.RequestOperatingCertRequest
	1, // 1: issuerservice.IssuerService.RequestOperatingCert:output_type -> issuerservice.RequestOperatingCertResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_issuer_proto_init() }
func file_api_issuer_proto_init() {
	if File_api_issuer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_issuer_proto_rawDesc), len(file_api_issuer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_issuer_proto_goTypes,
		DependencyIndexes: file_api_issuer_proto_depIdxs,
		MessageInfos:      file_api_issuer_proto_msgTypes,
	}.Build()
	File_api_issuer_proto = out.File
	file_api_issuer_proto_goTypes = nil
	file_api_issuer_proto_depIdxs = nil
}
