// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/issuer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IssuerService_RequestOperatingCert_FullMethodName = "/issuerservice.IssuerService/RequestOperatingCert"
)

// IssuerServiceClient is the client API for IssuerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IssuerService is the sole RPC surface a bootstrapped node calls to keep
// its operating certificate fresh. The caller's hostname is never a field
// on this message -- it is always derived from the verified mTLS peer
// identity, exactly like every other authenticated RPC in this project.
type IssuerServiceClient interface {
	RequestOperatingCert(ctx context.Context, in *RequestOperatingCertRequest, opts ...grpc.CallOption) (*RequestOperatingCertResponse, error)
}

type issuerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIssuerServiceClient(cc grpc.ClientConnInterface) IssuerServiceClient {
	return &issuerServiceClient{cc}
}

func (c *issuerServiceClient) RequestOperatingCert(ctx context.Context, in *RequestOperatingCertRequest, opts ...grpc.CallOption) (*RequestOperatingCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestOperatingCertResponse)
	err := c.cc.Invoke(ctx, IssuerService_RequestOperatingCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IssuerServiceServer is the server API for IssuerService service.
// All implementations must embed UnimplementedIssuerServiceServer
// for forward compatibility.
//
// IssuerService is the sole RPC surface a bootstrapped node calls to keep
// its operating certificate fresh. The caller's hostname is never a field
// on this message -- it is always derived from the verified mTLS peer
// identity, exactly like every other authenticated RPC in this project.
type IssuerServiceServer interface {
	RequestOperatingCert(context.Context, *RequestOperatingCertRequest) (*RequestOperatingCertResponse, error)
	mustEmbedUnimplementedIssuerServiceServer()
}

// UnimplementedIssuerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIssuerServiceServer struct{}

func (UnimplementedIssuerServiceServer) RequestOperatingCert(context.Context, *RequestOperatingCertRequest) (*RequestOperatingCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestOperatingCert not implemented")
}
func (UnimplementedIssuerServiceServer) mustEmbedUnimplementedIssuerServiceServer() {}
func (UnimplementedIssuerServiceServer) testEmbeddedByValue()                       {}

// UnsafeIssuerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IssuerServiceServer will
// result in compilation errors.
type UnsafeIssuerServiceServer interface {
	mustEmbedUnimplementedIssuerServiceServer()
}

func RegisterIssuerServiceServer(s grpc.ServiceRegistrar, srv IssuerServiceServer) {
	// If the following call panics, it indicates UnimplementedIssuerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IssuerService_ServiceDesc, srv)
}

func _IssuerService_RequestOperatingCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestOperatingCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IssuerServiceServer).RequestOperatingCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IssuerService_RequestOperatingCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IssuerServiceServer).RequestOperatingCert(ctx, req.(*RequestOperatingCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IssuerService_ServiceDesc is the grpc.ServiceDesc for IssuerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IssuerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "issuerservice.IssuerService",
	HandlerType: (*IssuerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestOperatingCert",
			Handler:    _IssuerService_RequestOperatingCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/issuer.proto",
}
