// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/issuer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestOperatingCertRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DER-encoded PKCS#10 certificate signing request. The caller's private
	// key never leaves the caller -- only the CSR crosses the wire.
	CsrDer        []byte `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOperatingCertRequest) Reset() {
	*x = RequestOperatingCertRequest{}
	mi := &file_api_issuer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOperatingCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOperatingCertRequest) ProtoMessage() {}

func (x *RequestOperatingCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_issuer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOperatingCertRequest.ProtoReflect.Descriptor instead.
func (*RequestOperatingCertRequest) Descriptor() ([]byte, []int) {
	return file_api_issuer_proto_rawDescGZIP(), []int{0}
}

func (x *RequestOperatingCertRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type RequestOperatingCertResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full certificate chain (leaf + any intermediates), PEM-encoded,
	// concatenated in order -- ready to write directly to client.crt.
	CertChainPem  []byte `protobuf:"bytes,1,opt,name=cert_chain_pem,json=certChainPem,proto3" json:"cert_chain_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOperatingCertResponse) Reset() {
	*x = RequestOperatingCertResponse{}
	mi := &file_api_issuer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOperatingCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOperatingCertResponse) ProtoMessage() {}

func (x *RequestOperatingCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_issuer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOperatingCertResponse.ProtoReflect.Descriptor instead.
func (*RequestOperatingCertResponse) Descriptor() ([]byte, []int) {
	return file_api_issuer_proto_rawDescGZIP(), []int{1}
}

func (x *RequestOperatingCertResponse) GetCertChainPem() []byte {
	if x != nil {
		return x.CertChainPem
	}
	return nil
}

type DescribeSANsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeSANsRequest) Reset() {
	*x = DescribeSANsRequest{}
	mi := &file_api_issuer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeSANsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeSANsRequest) ProtoMessage() {}

func (x *DescribeSANsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_issuer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeSANsRequest.ProtoReflect.Descriptor instead.
func (*DescribeSANsRequest) Descriptor() ([]byte, []int) {
	return file_api_issuer_proto_rawDescGZIP(), []int{2}
}

type DescribeSANsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current SAN aliases for the caller's own hostname (never including the
	// hostname itself, which the caller always places in the CSR's own
	// Subject.CommonName). Must be requested and used verbatim as a CSR's
	// DNSNames before calling RequestOperatingCert: step-ca's OTT provisioner
	// validates a CSR's requested DNS SANs against the signing token's
	// authorized set with an exact match, not a subset (confirmed against
	// smallstep/certificates@v0.30.2's authority/provisioner/sign_options.go
	// dnsNamesValidator) -- there is no way to learn or guess this list
	// without asking.
	Sans          []string `protobuf:"bytes,1,rep,name=sans,proto3" json:"sans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeSANsResponse) Reset() {
	*x = DescribeSANsResponse{}
	mi := &file_api_issuer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeSANsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeSANsResponse) ProtoMessage() {}

func (x *DescribeSANsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_issuer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeSANsResponse.ProtoReflect.Descriptor instead.
func (*DescribeSANsResponse) Descriptor() ([]byte, []int) {
	return file_api_issuer_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeSANsResponse) GetSans() []string {
	if x != nil {
		return x.Sans
	}
	return nil
}

var File_api_issuer_proto protoreflect.FileDescriptor

const file_api_issuer_proto_rawDesc = "" +
	"\n" +
	"\x10api/issuer.proto\x12\rissuerservice\"6\n" +
	"\x1bRequestOperatingCertRequest\x12\x17\n" +
	"\acsr_der\x18\x01 \x01(\fR\x06csrDer\"D\n" +
	"\x1cRequestOperatingCertResponse\x12$\n" +
	"\x0ecert_chain_pem\x18\x01 \x01(\fR\fcertChainPem\"\x15\n" +
	"\x13DescribeSANsRequest\"*\n" +
	"\x14DescribeSANsResponse\x12\x12\n" +
	"\x04sans\x18\x01 \x03(\tR\x04sans2\xd9\x01\n" +
	"\rIssuerService\x12o\n" +
	"\x14RequestOperatingCert\x12*.issuerservice.RequestOperatingCertRequest\x1a+.issuerservice.RequestOperatingCertResponse\x12W\n" +
	"\fDescribeSANs\x12\".issuerservice.DescribeSANsRequest\x1a#.issuerservice.DescribeSANsResponseB\tZ\a./protob\x06proto3"

var (
	file_api_issuer_proto_rawDescOnce sync.Once
	file_api_issuer_proto_rawDescData []byte
)

func file_api_issuer_proto_rawDescGZIP() []byte {
	file_api_issuer_proto_rawDescOnce.Do(func() {
		file_api_issuer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_issuer_proto_rawDesc), len(file_api_issuer_proto_rawDesc)))
	})
	return file_api_issuer_proto_rawDescData
}

var file_api_issuer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_issuer_proto_goTypes = []any{
	(*RequestOperatingCertRequest)(nil),  // 0: issuerservice.RequestOperatingCertRequest
	(*RequestOperatingCertResponse)(nil), // 1: issuerservice.RequestOperatingCertResponse
	(*DescribeSANsRequest)(nil),          // 2: issuerservice.DescribeSANsRequest
	(*DescribeSANsResponse)(nil),         // 3: issuerservice.DescribeSANsResponse
}
var file_api_issuer_proto_depIdxs = []int32{
	0, // 0: issuerservice.IssuerService.RequestOperatingCert:input_type -> issuerservice.RequestOperatingCertRequest
	2, // 1: issuerservice.IssuerService.DescribeSANs:input_type -> issuerservice.DescribeSANsRequest
	1, // 2: issuerservice.IssuerService.RequestOperatingCert:output_type -> issuerservice.RequestOperatingCertResponse
	3, // 3: issuerservice.IssuerService.DescribeSANs:output_type -> issuerservice.DescribeSANsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_issuer_proto_init() }
func file_api_issuer_proto_init() {
	if File_api_issuer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_issuer_proto_rawDesc), len(file_api_issuer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_issuer_proto_goTypes,
		DependencyIndexes: file_api_issuer_proto_depIdxs,
		MessageInfos:      file_api_issuer_proto_msgTypes,
	}.Build()
	File_api_issuer_proto = out.File
	file_api_issuer_proto_goTypes = nil
	file_api_issuer_proto_depIdxs = nil
}
