// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/jobstatus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPolicyJobStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Lower bound for the Loki query. api-server clamps this to at most
	// maxJobsWindow (168h) before "now" -- a policy legitimately older than
	// that is still searched, just over a narrower recent window, since a
	// job that finishes at any point is always inside a future tick's
	// window regardless of how old the policy is.
	PolicyCreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=policy_created_at,json=policyCreatedAt,proto3" json:"policy_created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPolicyJobStatusRequest) Reset() {
	*x = GetPolicyJobStatusRequest{}
	mi := &file_api_jobstatus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyJobStatusRequest) ProtoMessage() {}

func (x *GetPolicyJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_jobstatus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_jobstatus_proto_rawDescGZIP(), []int{0}
}

func (x *GetPolicyJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetPolicyJobStatusRequest) GetPolicyCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PolicyCreatedAt
	}
	return nil
}

type GetPolicyJobStatusResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Finished bool                   `protobuf:"varint,1,opt,name=finished,proto3" json:"finished,omitempty"`
	// Set iff finished is true.
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyJobStatusResponse) Reset() {
	*x = GetPolicyJobStatusResponse{}
	mi := &file_api_jobstatus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyJobStatusResponse) ProtoMessage() {}

func (x *GetPolicyJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_jobstatus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_jobstatus_proto_rawDescGZIP(), []int{1}
}

func (x *GetPolicyJobStatusResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *GetPolicyJobStatusResponse) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var File_api_jobstatus_proto protoreflect.FileDescriptor

const file_api_jobstatus_proto_rawDesc = "" +
	"\n" +
	"\x13api/jobstatus.proto\x12\x10jobstatusservice\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n" +
	"\x19GetPolicyJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12F\n" +
	"\x11policy_created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0fpolicyCreatedAt\"u\n" +
	"\x1aGetPolicyJobStatusResponse\x12\x1a\n" +
	"\bfinished\x18\x01 \x01(\bR\bfinished\x12;\n" +
	"\vfinished_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt2\x83\x01\n" +
	"\x10JobStatusService\x12o\n" +
	"\x12GetPolicyJobStatus\x12+.jobstatusservice.GetPolicyJobStatusRequest\x1a,.jobstatusservice.GetPolicyJobStatusResponseB\tZ\a./protob\x06proto3"

var (
	file_api_jobstatus_proto_rawDescOnce sync.Once
	file_api_jobstatus_proto_rawDescData []byte
)

func file_api_jobstatus_proto_rawDescGZIP() []byte {
	file_api_jobstatus_proto_rawDescOnce.Do(func() {
		file_api_jobstatus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_jobstatus_proto_rawDesc), len(file_api_jobstatus_proto_rawDesc)))
	})
	return file_api_jobstatus_proto_rawDescData
}

var file_api_jobstatus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_jobstatus_proto_goTypes = []any{
	(*GetPolicyJobStatusRequest)(nil),  // 0: jobstatusservice.GetPolicyJobStatusRequest
	(*GetPolicyJobStatusResponse)(nil), // 1: jobstatusservice.GetPolicyJobStatusResponse
	(*timestamppb.Timestamp)(nil),      // 2: google.protobuf.Timestamp
}
var file_api_jobstatus_proto_depIdxs = []int32{
	2, // 0: jobstatusservice.GetPolicyJobStatusRequest.policy_created_at:type_name -> google.protobuf.Timestamp
	2, // 1: jobstatusservice.GetPolicyJobStatusResponse.finished_at:type_name -> google.protobuf.Timestamp
	0, // 2: jobstatusservice.JobStatusService.GetPolicyJobStatus:input_type -> jobstatusservice.GetPolicyJobStatusRequest
	1, // 3: jobstatusservice.JobStatusService.GetPolicyJobStatus:output_type -> jobstatusservice.GetPolicyJobStatusResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_jobstatus_proto_init() }
func file_api_jobstatus_proto_init() {
	if File_api_jobstatus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_jobstatus_proto_rawDesc), len(file_api_jobstatus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_jobstatus_proto_goTypes,
		DependencyIndexes: file_api_jobstatus_proto_depIdxs,
		MessageInfos:      file_api_jobstatus_proto_msgTypes,
	}.Build()
	File_api_jobstatus_proto = out.File
	file_api_jobstatus_proto_goTypes = nil
	file_api_jobstatus_proto_depIdxs = nil
}
