// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/jobstatus.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobStatusService_GetPolicyJobStatus_FullMethodName = "/jobstatusservice.JobStatusService/GetPolicyJobStatus"
)

// JobStatusServiceClient is the client API for JobStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobStatusService is api-server's sole gRPC surface (its REST API remains
// the deliberate non-mTLS surface for browsers/admin tools -- see
// docs/components/api-server.md). It answers one question for
// policy-server's restore-policy cleanup sweep: has a given job_id's Loki
// event=finish line been observed? Restricted to the "control-plane" role.
type JobStatusServiceClient interface {
	GetPolicyJobStatus(ctx context.Context, in *GetPolicyJobStatusRequest, opts ...grpc.CallOption) (*GetPolicyJobStatusResponse, error)
}

type jobStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobStatusServiceClient(cc grpc.ClientConnInterface) JobStatusServiceClient {
	return &jobStatusServiceClient{cc}
}

func (c *jobStatusServiceClient) GetPolicyJobStatus(ctx context.Context, in *GetPolicyJobStatusRequest, opts ...grpc.CallOption) (*GetPolicyJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPolicyJobStatusResponse)
	err := c.cc.Invoke(ctx, JobStatusService_GetPolicyJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobStatusServiceServer is the server API for JobStatusService service.
// All implementations must embed UnimplementedJobStatusServiceServer
// for forward compatibility.
//
// JobStatusService is api-server's sole gRPC surface (its REST API remains
// the deliberate non-mTLS surface for browsers/admin tools -- see
// docs/components/api-server.md). It answers one question for
// policy-server's restore-policy cleanup sweep: has a given job_id's Loki
// event=finish line been observed? Restricted to the "control-plane" role.
type JobStatusServiceServer interface {
	GetPolicyJobStatus(context.Context, *GetPolicyJobStatusRequest) (*GetPolicyJobStatusResponse, error)
	mustEmbedUnimplementedJobStatusServiceServer()
}

// UnimplementedJobStatusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobStatusServiceServer struct{}

func (UnimplementedJobStatusServiceServer) GetPolicyJobStatus(context.Context, *GetPolicyJobStatusRequest) (*GetPolicyJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicyJobStatus not implemented")
}
func (UnimplementedJobStatusServiceServer) mustEmbedUnimplementedJobStatusServiceServer() {}
func (UnimplementedJobStatusServiceServer) testEmbeddedByValue()                          {}

// UnsafeJobStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobStatusServiceServer will
// result in compilation errors.
type UnsafeJobStatusServiceServer interface {
	mustEmbedUnimplementedJobStatusServiceServer()
}

func RegisterJobStatusServiceServer(s grpc.ServiceRegistrar, srv JobStatusServiceServer) {
	// If the following call panics, it indicates UnimplementedJobStatusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobStatusService_ServiceDesc, srv)
}

func _JobStatusService_GetPolicyJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobStatusServiceServer).GetPolicyJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobStatusService_GetPolicyJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobStatusServiceServer).GetPolicyJobStatus(ctx, req.(*GetPolicyJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobStatusService_ServiceDesc is the grpc.ServiceDesc for JobStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobstatusservice.JobStatusService",
	HandlerType: (*JobStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPolicyJobStatus",
			Handler:    _JobStatusService_GetPolicyJobStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/jobstatus.proto",
}
