// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/list.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ListService_ListFiles_FullMethodName           = "/listservice.ListService/ListFiles"
	ListService_ResolveRestoreFiles_FullMethodName = "/listservice.ListService/ResolveRestoreFiles"
)

// ListServiceClient is the client API for ListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListServiceClient interface {
	ListFiles(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileRow], error)
	// ResolveRestoreFiles resolves a batch of restore-rule-shaped filters
	// directly, scoped by host/path/timeframe, instead of the unbounded dump
	// ListFiles would require for the same job. Server-streaming: one
	// response per resolved row, so a filter matching millions of rows never
	// has to be buffered whole on either side. See
	// docs/protocols/list.md#resolverestorefiles.
	ResolveRestoreFiles(ctx context.Context, in *ResolveRestoreFilesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResolveRestoreFilesResponse], error)
}

type listServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListServiceClient(cc grpc.ClientConnInterface) ListServiceClient {
	return &listServiceClient{cc}
}

func (c *listServiceClient) ListFiles(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileRow], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ListService_ServiceDesc.Streams[0], ListService_ListFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListRequest, FileRow]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ListService_ListFilesClient = grpc.ServerStreamingClient[FileRow]

func (c *listServiceClient) ResolveRestoreFiles(ctx context.Context, in *ResolveRestoreFilesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResolveRestoreFilesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ListService_ServiceDesc.Streams[1], ListService_ResolveRestoreFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResolveRestoreFilesRequest, ResolveRestoreFilesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ListService_ResolveRestoreFilesClient = grpc.ServerStreamingClient[ResolveRestoreFilesResponse]

// ListServiceServer is the server API for ListService service.
// All implementations must embed UnimplementedListServiceServer
// for forward compatibility.
type ListServiceServer interface {
	ListFiles(*ListRequest, grpc.ServerStreamingServer[FileRow]) error
	// ResolveRestoreFiles resolves a batch of restore-rule-shaped filters
	// directly, scoped by host/path/timeframe, instead of the unbounded dump
	// ListFiles would require for the same job. Server-streaming: one
	// response per resolved row, so a filter matching millions of rows never
	// has to be buffered whole on either side. See
	// docs/protocols/list.md#resolverestorefiles.
	ResolveRestoreFiles(*ResolveRestoreFilesRequest, grpc.ServerStreamingServer[ResolveRestoreFilesResponse]) error
	mustEmbedUnimplementedListServiceServer()
}

// UnimplementedListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedListServiceServer struct{}

func (UnimplementedListServiceServer) ListFiles(*ListRequest, grpc.ServerStreamingServer[FileRow]) error {
	return status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedListServiceServer) ResolveRestoreFiles(*ResolveRestoreFilesRequest, grpc.ServerStreamingServer[ResolveRestoreFilesResponse]) error {
	return status.Error(codes.Unimplemented, "method ResolveRestoreFiles not implemented")
}
func (UnimplementedListServiceServer) mustEmbedUnimplementedListServiceServer() {}
func (UnimplementedListServiceServer) testEmbeddedByValue()                     {}

// UnsafeListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListServiceServer will
// result in compilation errors.
type UnsafeListServiceServer interface {
	mustEmbedUnimplementedListServiceServer()
}

func RegisterListServiceServer(s grpc.ServiceRegistrar, srv ListServiceServer) {
	// If the following call panics, it indicates UnimplementedListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ListService_ServiceDesc, srv)
}

func _ListService_ListFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ListServiceServer).ListFiles(m, &grpc.GenericServerStream[ListRequest, FileRow]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ListService_ListFilesServer = grpc.ServerStreamingServer[FileRow]

func _ListService_ResolveRestoreFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResolveRestoreFilesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ListServiceServer).ResolveRestoreFiles(m, &grpc.GenericServerStream[ResolveRestoreFilesRequest, ResolveRestoreFilesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ListService_ResolveRestoreFilesServer = grpc.ServerStreamingServer[ResolveRestoreFilesResponse]

// ListService_ServiceDesc is the grpc.ServiceDesc for ListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "listservice.ListService",
	HandlerType: (*ListServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFiles",
			Handler:       _ListService_ListFiles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ResolveRestoreFiles",
			Handler:       _ListService_ResolveRestoreFiles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/list.proto",
}
