// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/list.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"` // source hostname filter; empty = all sources
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                               // prefix filter on file path; empty = no filter
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`                           // free-text substring filter; empty = no filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_list_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type FileRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUuid      string                 `protobuf:"bytes,1,opt,name=file_uuid,json=fileUuid,proto3" json:"file_uuid,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Chunks        int32                  `protobuf:"varint,7,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Versions      int64                  `protobuf:"varint,8,opt,name=versions,proto3" json:"versions,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339 UTC, matches listformat's JSON rendering
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRow) Reset() {
	*x = FileRow{}
	mi := &file_api_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRow) ProtoMessage() {}

func (x *FileRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRow.ProtoReflect.Descriptor instead.
func (*FileRow) Descriptor() ([]byte, []int) {
	return file_api_list_proto_rawDescGZIP(), []int{1}
}

func (x *FileRow) GetFileUuid() string {
	if x != nil {
		return x.FileUuid
	}
	return ""
}

func (x *FileRow) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FileRow) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileRow) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRow) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FileRow) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileRow) GetChunks() int32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

func (x *FileRow) GetVersions() int64 {
	if x != nil {
		return x.Versions
	}
	return 0
}

func (x *FileRow) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// RestoreFileFilter is one restore rule's selection criteria, sent as-is
// (only included rules become filters -- exclude rules never need file
// data, see docs/protocols/list.md#resolverestorefiles).
type RestoreFileFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"` // "" = host-agnostic (folder rule)
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	PathIsPrefix  bool                   `protobuf:"varint,3,opt,name=path_is_prefix,json=pathIsPrefix,proto3" json:"path_is_prefix,omitempty"` // true = folder rule (recursive subtree), false = exact file rule
	NotBefore     int64                  `protobuf:"varint,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`            // 0 = unbounded
	NotAfter      int64                  `protobuf:"varint,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`               // 0 = unbounded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreFileFilter) Reset() {
	*x = RestoreFileFilter{}
	mi := &file_api_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFileFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFileFilter) ProtoMessage() {}

func (x *RestoreFileFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFileFilter.ProtoReflect.Descriptor instead.
func (*RestoreFileFilter) Descriptor() ([]byte, []int) {
	return file_api_list_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreFileFilter) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RestoreFileFilter) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RestoreFileFilter) GetPathIsPrefix() bool {
	if x != nil {
		return x.PathIsPrefix
	}
	return false
}

func (x *RestoreFileFilter) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *RestoreFileFilter) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

type ResolveRestoreFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       []*RestoreFileFilter   `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRestoreFilesRequest) Reset() {
	*x = ResolveRestoreFilesRequest{}
	mi := &file_api_list_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRestoreFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRestoreFilesRequest) ProtoMessage() {}

func (x *ResolveRestoreFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_list_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRestoreFilesRequest.ProtoReflect.Descriptor instead.
func (*ResolveRestoreFilesRequest) Descriptor() ([]byte, []int) {
	return file_api_list_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveRestoreFilesRequest) GetFilters() []*RestoreFileFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ResolveRestoreFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           *FileRow               `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	FilterIndex   int32                  `protobuf:"varint,2,opt,name=filter_index,json=filterIndex,proto3" json:"filter_index,omitempty"` // index into the request's filters -- which filter resolved this row
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRestoreFilesResponse) Reset() {
	*x = ResolveRestoreFilesResponse{}
	mi := &file_api_list_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRestoreFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRestoreFilesResponse) ProtoMessage() {}

func (x *ResolveRestoreFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_list_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRestoreFilesResponse.ProtoReflect.Descriptor instead.
func (*ResolveRestoreFilesResponse) Descriptor() ([]byte, []int) {
	return file_api_list_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveRestoreFilesResponse) GetRow() *FileRow {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *ResolveRestoreFilesResponse) GetFilterIndex() int32 {
	if x != nil {
		return x.FilterIndex
	}
	return 0
}

var File_api_list_proto protoreflect.FileDescriptor

const file_api_list_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/list.proto\x12\vlistservice\"Z\n" +
	"\vListRequest\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"\xeb\x01\n" +
	"\aFileRow\x12\x1b\n" +
	"\tfile_uuid\x18\x01 \x01(\tR\bfileUuid\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x16\n" +
	"\x06chunks\x18\a \x01(\x05R\x06chunks\x12\x1a\n" +
	"\bversions\x18\b \x01(\x03R\bversions\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"\x9d\x01\n" +
	"\x11RestoreFileFilter\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12$\n" +
	"\x0epath_is_prefix\x18\x03 \x01(\bR\fpathIsPrefix\x12\x1d\n" +
	"\n" +
	"not_before\x18\x04 \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x05 \x01(\x03R\bnotAfter\"V\n" +
	"\x1aResolveRestoreFilesRequest\x128\n" +
	"\afilters\x18\x01 \x03(\v2\x1e.listservice.RestoreFileFilterR\afilters\"h\n" +
	"\x1bResolveRestoreFilesResponse\x12&\n" +
	"\x03row\x18\x01 \x01(\v2\x14.listservice.FileRowR\x03row\x12!\n" +
	"\ffilter_index\x18\x02 \x01(\x05R\vfilterIndex2\xb8\x01\n" +
	"\vListService\x12=\n" +
	"\tListFiles\x12\x18.listservice.ListRequest\x1a\x14.listservice.FileRow0\x01\x12j\n" +
	"\x13ResolveRestoreFiles\x12'.listservice.ResolveRestoreFilesRequest\x1a(.listservice.ResolveRestoreFilesResponse0\x01B\tZ\a./protob\x06proto3"

var (
	file_api_list_proto_rawDescOnce sync.Once
	file_api_list_proto_rawDescData []byte
)

func file_api_list_proto_rawDescGZIP() []byte {
	file_api_list_proto_rawDescOnce.Do(func() {
		file_api_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_list_proto_rawDesc), len(file_api_list_proto_rawDesc)))
	})
	return file_api_list_proto_rawDescData
}

var file_api_list_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_list_proto_goTypes = []any{
	(*ListRequest)(nil),                 // 0: listservice.ListRequest
	(*FileRow)(nil),                     // 1: listservice.FileRow
	(*RestoreFileFilter)(nil),           // 2: listservice.RestoreFileFilter
	(*ResolveRestoreFilesRequest)(nil),  // 3: listservice.ResolveRestoreFilesRequest
	(*ResolveRestoreFilesResponse)(nil), // 4: listservice.ResolveRestoreFilesResponse
}
var file_api_list_proto_depIdxs = []int32{
	2, // 0: listservice.ResolveRestoreFilesRequest.filters:type_name -> listservice.RestoreFileFilter
	1, // 1: listservice.ResolveRestoreFilesResponse.row:type_name -> listservice.FileRow
	0, // 2: listservice.ListService.ListFiles:input_type -> listservice.ListRequest
	3, // 3: listservice.ListService.ResolveRestoreFiles:input_type -> listservice.ResolveRestoreFilesRequest
	1, // 4: listservice.ListService.ListFiles:output_type -> listservice.FileRow
	4, // 5: listservice.ListService.ResolveRestoreFiles:output_type -> listservice.ResolveRestoreFilesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_list_proto_init() }
func file_api_list_proto_init() {
	if File_api_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_list_proto_rawDesc), len(file_api_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_list_proto_goTypes,
		DependencyIndexes: file_api_list_proto_depIdxs,
		MessageInfos:      file_api_list_proto_msgTypes,
	}.Build()
	File_api_list_proto = out.File
	file_api_list_proto_goTypes = nil
	file_api_list_proto_depIdxs = nil
}
