// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/list.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"` // source hostname filter; empty = all sources
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                               // prefix filter on file path; empty = no filter
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`                           // free-text substring filter; empty = no filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_list_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*FileRow             `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_list_proto_rawDescGZIP(), []int{1}
}

func (x *ListResponse) GetRows() []*FileRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type FileRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUuid      string                 `protobuf:"bytes,1,opt,name=file_uuid,json=fileUuid,proto3" json:"file_uuid,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Size          int64                  `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Chunks        int32                  `protobuf:"varint,7,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Versions      int64                  `protobuf:"varint,8,opt,name=versions,proto3" json:"versions,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339 UTC, matches listformat's JSON rendering
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRow) Reset() {
	*x = FileRow{}
	mi := &file_api_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRow) ProtoMessage() {}

func (x *FileRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRow.ProtoReflect.Descriptor instead.
func (*FileRow) Descriptor() ([]byte, []int) {
	return file_api_list_proto_rawDescGZIP(), []int{2}
}

func (x *FileRow) GetFileUuid() string {
	if x != nil {
		return x.FileUuid
	}
	return ""
}

func (x *FileRow) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FileRow) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileRow) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRow) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FileRow) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileRow) GetChunks() int32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

func (x *FileRow) GetVersions() int64 {
	if x != nil {
		return x.Versions
	}
	return 0
}

func (x *FileRow) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_api_list_proto protoreflect.FileDescriptor

const file_api_list_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/list.proto\x12\vlistservice\"Z\n" +
	"\vListRequest\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"8\n" +
	"\fListResponse\x12(\n" +
	"\x04rows\x18\x01 \x03(\v2\x14.listservice.FileRowR\x04rows\"\xeb\x01\n" +
	"\aFileRow\x12\x1b\n" +
	"\tfile_uuid\x18\x01 \x01(\tR\bfileUuid\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x16\n" +
	"\x06chunks\x18\a \x01(\x05R\x06chunks\x12\x1a\n" +
	"\bversions\x18\b \x01(\x03R\bversions\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt2O\n" +
	"\vListService\x12@\n" +
	"\tListFiles\x12\x18.listservice.ListRequest\x1a\x19.listservice.ListResponseB\tZ\a./protob\x06proto3"

var (
	file_api_list_proto_rawDescOnce sync.Once
	file_api_list_proto_rawDescData []byte
)

func file_api_list_proto_rawDescGZIP() []byte {
	file_api_list_proto_rawDescOnce.Do(func() {
		file_api_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_list_proto_rawDesc), len(file_api_list_proto_rawDesc)))
	})
	return file_api_list_proto_rawDescData
}

var file_api_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_list_proto_goTypes = []any{
	(*ListRequest)(nil),  // 0: listservice.ListRequest
	(*ListResponse)(nil), // 1: listservice.ListResponse
	(*FileRow)(nil),      // 2: listservice.FileRow
}
var file_api_list_proto_depIdxs = []int32{
	2, // 0: listservice.ListResponse.rows:type_name -> listservice.FileRow
	0, // 1: listservice.ListService.ListFiles:input_type -> listservice.ListRequest
	1, // 2: listservice.ListService.ListFiles:output_type -> listservice.ListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_list_proto_init() }
func file_api_list_proto_init() {
	if File_api_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_list_proto_rawDesc), len(file_api_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_list_proto_goTypes,
		DependencyIndexes: file_api_list_proto_depIdxs,
		MessageInfos:      file_api_list_proto_msgTypes,
	}.Build()
	File_api_list_proto = out.File
	file_api_list_proto_goTypes = nil
	file_api_list_proto_depIdxs = nil
}
