// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/policyserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoliciesRequest) Reset() {
	*x = GetPoliciesRequest{}
	mi := &file_api_policyserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoliciesRequest) ProtoMessage() {}

func (x *GetPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoliciesRequest.ProtoReflect.Descriptor instead.
func (*GetPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{0}
}

type GetPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*Policy              `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoliciesResponse) Reset() {
	*x = GetPoliciesResponse{}
	mi := &file_api_policyserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoliciesResponse) ProtoMessage() {}

func (x *GetPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoliciesResponse.ProtoReflect.Descriptor instead.
func (*GetPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetPoliciesResponse) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type ListPoliciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. "backup", "storage", or "restore" -- when set, only policies
	// of this type are returned. Empty returns every type (unfiltered,
	// today's behavior).
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_api_policyserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{2}
}

func (x *ListPoliciesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*Policy              `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_api_policyserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{3}
}

func (x *ListPoliciesResponse) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type ClientFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostnames     []string               `protobuf:"bytes,1,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFilters) Reset() {
	*x = ClientFilters{}
	mi := &file_api_policyserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFilters) ProtoMessage() {}

func (x *ClientFilters) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFilters.ProtoReflect.Descriptor instead.
func (*ClientFilters) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{4}
}

func (x *ClientFilters) GetHostnames() []string {
	if x != nil {
		return x.Hostnames
	}
	return nil
}

func (x *ClientFilters) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ObjectFilter struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Path    string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Include []string               `protobuf:"bytes,2,rep,name=include,proto3" json:"include,omitempty"`
	Exclude []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	// policy-server-computed, deterministic (see Policy.id). Not present in
	// the on-disk policy JSON schema.
	Id            string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectFilter) Reset() {
	*x = ObjectFilter{}
	mi := &file_api_policyserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectFilter) ProtoMessage() {}

func (x *ObjectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectFilter.ProtoReflect.Descriptor instead.
func (*ObjectFilter) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectFilter) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ObjectFilter) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *ObjectFilter) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *ObjectFilter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PolicyCheckin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyCheckin) Reset() {
	*x = PolicyCheckin{}
	mi := &file_api_policyserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyCheckin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyCheckin) ProtoMessage() {}

func (x *PolicyCheckin) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyCheckin.ProtoReflect.Descriptor instead.
func (*PolicyCheckin) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{6}
}

func (x *PolicyCheckin) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PolicyCheckin) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

// One restore-cart selection rule: host-agnostic (Host == "") folder rules
// and host-specific file rules resolve by longest-matching-path-ancestor,
// exactly like web/src/utils/restoreRules.js's resolveFile. policy-server
// never interprets these beyond the load-time validation in
// RestorePolicy.Validate (non-empty Path, dest_path/not_before/not_after
// only on an included rule); resolution happens at verify time, in rwfs.
type RestoreRule struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Host    string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"` // "" = host-agnostic, matches every source host
	Path    string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Include bool                   `protobuf:"varint,3,opt,name=include,proto3" json:"include,omitempty"`
	// Destination path to restore to, if different from path. Empty (or
	// equal to path) means "no rename -- restore to the original path."
	// Only meaningful when include is true; see RestorePolicy.Validate.
	DestPath string `protobuf:"bytes,4,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"`
	// Timeframe bounding which backed-up version of this rule's selection to
	// use: the latest version whose backup date falls inside
	// [not_before, not_after] wins; a version outside the window is ignored
	// entirely, never used as a fallback. Unix seconds; 0 = unbounded on
	// that side. Only meaningful when include is true; see
	// RestorePolicy.Validate.
	NotBefore     int64 `protobuf:"varint,5,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter      int64 `protobuf:"varint,6,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRule) Reset() {
	*x = RestoreRule{}
	mi := &file_api_policyserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRule) ProtoMessage() {}

func (x *RestoreRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRule.ProtoReflect.Descriptor instead.
func (*RestoreRule) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreRule) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RestoreRule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RestoreRule) GetInclude() bool {
	if x != nil {
		return x.Include
	}
	return false
}

func (x *RestoreRule) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

func (x *RestoreRule) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *RestoreRule) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ObjectFilters []*ObjectFilter        `protobuf:"bytes,4,rep,name=object_filters,json=objectFilters,proto3" json:"object_filters,omitempty"`
	// Duration string, e.g. "24h" (time.ParseDuration format). policy-server
	// never parses or evaluates this -- opaque pass-through data.
	Rpo string `protobuf:"bytes,5,opt,name=rpo,proto3" json:"rpo,omitempty"`
	// List of cron expressions (5-field). policy-server never parses or
	// evaluates these -- opaque pass-through data.
	BackupWindow []string `protobuf:"bytes,6,rep,name=backup_window,json=backupWindow,proto3" json:"backup_window,omitempty"`
	// policy-server-computed, deterministic from the policy file's name --
	// stable across reloads, changes only if the file is renamed. Not
	// present in the on-disk policy JSON schema.
	Id string `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	// Only ever populated by ListPolicies/CreatePolicy/UpdatePolicy -- omitted
	// by GetPolicies so a node never learns another node's targeting rules
	// from a policy that already matched its own identity.
	ClientFilters *ClientFilters `protobuf:"bytes,9,opt,name=client_filters,json=clientFilters,proto3" json:"client_filters,omitempty"`
	// Derived from the name of the subfolder the policy file was loaded from
	// (e.g. "backup" for policies/backup/*.json) -- never read from or
	// written to the on-disk policy JSON. Populated by both GetPolicies and
	// ListPolicies.
	Type string `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"`
	// storage policy only.
	Port int32 `protobuf:"varint,12,opt,name=port,proto3" json:"port,omitempty"`
	// "storage" policy only -- opaque JSON text, verbatim passthrough. Never
	// parsed or interpreted by policy-server beyond checking
	// well-formedness. A "restore" policy carries no config: its selection
	// lives in the structured rules field (19) instead, as of 2026-08-10.
	Config string `protobuf:"bytes,13,opt,name=config,proto3" json:"config,omitempty"`
	// Zero/unset means never disabled. Once this time passes, GetPolicies
	// stops returning the policy (checked live, not cached); ListPolicies is
	// unaffected. Generic across every policy type -- policy-server attaches
	// no meaning to *why* a policy is disabled.
	DisabledAt *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=disabled_at,json=disabledAt,proto3" json:"disabled_at,omitempty"`
	// "backup" and "restore" policy only, required. References a
	// "storage"-typed Policy.id; destination is resolved from it live on
	// every read.
	StoragePolicyId string           `protobuf:"bytes,15,opt,name=storage_policy_id,json=storagePolicyId,proto3" json:"storage_policy_id,omitempty"`
	Checkins        []*PolicyCheckin `protobuf:"bytes,16,rep,name=checkins,proto3" json:"checkins,omitempty"` // ListPolicies only -- see below
	// "backup" and "restore" policy only. Derived, read-only: one
	// "host:port" entry per live checkin against storage_policy_id, freshest
	// checkin first. Empty if the storage policy has no checkins yet or
	// storage_policy_id is dangling. Unset for a "storage" policy, as
	// before. For "restore" these are the stores to verify against, not
	// write to.
	Destinations []string `protobuf:"bytes,17,rep,name=destinations,proto3" json:"destinations,omitempty"`
	// "restore" policy only.
	Rules         []*RestoreRule `protobuf:"bytes,19,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_api_policyserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{8}
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Policy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Policy) GetObjectFilters() []*ObjectFilter {
	if x != nil {
		return x.ObjectFilters
	}
	return nil
}

func (x *Policy) GetRpo() string {
	if x != nil {
		return x.Rpo
	}
	return ""
}

func (x *Policy) GetBackupWindow() []string {
	if x != nil {
		return x.BackupWindow
	}
	return nil
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetClientFilters() *ClientFilters {
	if x != nil {
		return x.ClientFilters
	}
	return nil
}

func (x *Policy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Policy) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Policy) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Policy) GetDisabledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisabledAt
	}
	return nil
}

func (x *Policy) GetStoragePolicyId() string {
	if x != nil {
		return x.StoragePolicyId
	}
	return ""
}

func (x *Policy) GetCheckins() []*PolicyCheckin {
	if x != nil {
		return x.Checkins
	}
	return nil
}

func (x *Policy) GetDestinations() []string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *Policy) GetRules() []*RestoreRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type CreatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ClientFilters *ClientFilters         `protobuf:"bytes,2,opt,name=client_filters,json=clientFilters,proto3" json:"client_filters,omitempty"`
	// Any id set on an entry here is ignored -- object filter IDs are always
	// server-computed from their position in this list.
	ObjectFilters []*ObjectFilter `protobuf:"bytes,3,rep,name=object_filters,json=objectFilters,proto3" json:"object_filters,omitempty"`
	Rpo           string          `protobuf:"bytes,4,opt,name=rpo,proto3" json:"rpo,omitempty"`
	BackupWindow  []string        `protobuf:"bytes,5,rep,name=backup_window,json=backupWindow,proto3" json:"backup_window,omitempty"`
	// "backup", "storage", or "restore" -- required. Determines which of the
	// type-specific fields are valid; mixing fields across types is rejected
	// (e.g. a "restore" request must not set object_filters/rpo/
	// backup_window/port/config).
	Type       string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Port       int32                  `protobuf:"varint,9,opt,name=port,proto3" json:"port,omitempty"`
	Config     string                 `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	DisabledAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=disabled_at,json=disabledAt,proto3" json:"disabled_at,omitempty"`
	// "backup" and "restore", both required.
	StoragePolicyId string `protobuf:"bytes,12,opt,name=storage_policy_id,json=storagePolicyId,proto3" json:"storage_policy_id,omitempty"`
	// "restore" policy only, required.
	Rules         []*RestoreRule `protobuf:"bytes,14,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	mi := &file_api_policyserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePolicyRequest) GetClientFilters() *ClientFilters {
	if x != nil {
		return x.ClientFilters
	}
	return nil
}

func (x *CreatePolicyRequest) GetObjectFilters() []*ObjectFilter {
	if x != nil {
		return x.ObjectFilters
	}
	return nil
}

func (x *CreatePolicyRequest) GetRpo() string {
	if x != nil {
		return x.Rpo
	}
	return ""
}

func (x *CreatePolicyRequest) GetBackupWindow() []string {
	if x != nil {
		return x.BackupWindow
	}
	return nil
}

func (x *CreatePolicyRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreatePolicyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CreatePolicyRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *CreatePolicyRequest) GetDisabledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisabledAt
	}
	return nil
}

func (x *CreatePolicyRequest) GetStoragePolicyId() string {
	if x != nil {
		return x.StoragePolicyId
	}
	return ""
}

func (x *CreatePolicyRequest) GetRules() []*RestoreRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UpdatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ClientFilters *ClientFilters         `protobuf:"bytes,3,opt,name=client_filters,json=clientFilters,proto3" json:"client_filters,omitempty"`
	// Full replacement of object_filters, not a patch -- reordering or
	// inserting entries changes the affected filters' ids.
	ObjectFilters []*ObjectFilter        `protobuf:"bytes,4,rep,name=object_filters,json=objectFilters,proto3" json:"object_filters,omitempty"`
	Rpo           string                 `protobuf:"bytes,5,opt,name=rpo,proto3" json:"rpo,omitempty"`
	BackupWindow  []string               `protobuf:"bytes,6,rep,name=backup_window,json=backupWindow,proto3" json:"backup_window,omitempty"`
	Port          int32                  `protobuf:"varint,9,opt,name=port,proto3" json:"port,omitempty"`
	Config        string                 `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	DisabledAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=disabled_at,json=disabledAt,proto3" json:"disabled_at,omitempty"`
	// "backup" only, required.
	StoragePolicyId string `protobuf:"bytes,12,opt,name=storage_policy_id,json=storagePolicyId,proto3" json:"storage_policy_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePolicyRequest) Reset() {
	*x = UpdatePolicyRequest{}
	mi := &file_api_policyserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyRequest) ProtoMessage() {}

func (x *UpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePolicyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePolicyRequest) GetClientFilters() *ClientFilters {
	if x != nil {
		return x.ClientFilters
	}
	return nil
}

func (x *UpdatePolicyRequest) GetObjectFilters() []*ObjectFilter {
	if x != nil {
		return x.ObjectFilters
	}
	return nil
}

func (x *UpdatePolicyRequest) GetRpo() string {
	if x != nil {
		return x.Rpo
	}
	return ""
}

func (x *UpdatePolicyRequest) GetBackupWindow() []string {
	if x != nil {
		return x.BackupWindow
	}
	return nil
}

func (x *UpdatePolicyRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *UpdatePolicyRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *UpdatePolicyRequest) GetDisabledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisabledAt
	}
	return nil
}

func (x *UpdatePolicyRequest) GetStoragePolicyId() string {
	if x != nil {
		return x.StoragePolicyId
	}
	return ""
}

type DeletePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_api_policyserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePolicyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyResponse) Reset() {
	*x = DeletePolicyResponse{}
	mi := &file_api_policyserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyResponse) ProtoMessage() {}

func (x *DeletePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyResponse.ProtoReflect.Descriptor instead.
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{12}
}

var File_api_policyserver_proto protoreflect.FileDescriptor

const file_api_policyserver_proto_rawDesc = "" +
	"\n" +
	"\x16api/policyserver.proto\x12\x13policyserverservice\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12GetPoliciesRequest\"N\n" +
	"\x13GetPoliciesResponse\x127\n" +
	"\bpolicies\x18\x01 \x03(\v2\x1b.policyserverservice.PolicyR\bpolicies\")\n" +
	"\x13ListPoliciesRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"O\n" +
	"\x14ListPoliciesResponse\x127\n" +
	"\bpolicies\x18\x01 \x03(\v2\x1b.policyserverservice.PolicyR\bpolicies\"\xb0\x01\n" +
	"\rClientFilters\x12\x1c\n" +
	"\thostnames\x18\x01 \x03(\tR\thostnames\x12F\n" +
	"\x06labels\x18\x02 \x03(\v2..policyserverservice.ClientFilters.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\fObjectFilter\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\ainclude\x18\x02 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"i\n" +
	"\rPolicyCheckin\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12<\n" +
	"\flast_seen_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"\xa8\x01\n" +
	"\vRestoreRule\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\ainclude\x18\x03 \x01(\bR\ainclude\x12\x1b\n" +
	"\tdest_path\x18\x04 \x01(\tR\bdestPath\x12\x1d\n" +
	"\n" +
	"not_before\x18\x05 \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x06 \x01(\x03R\bnotAfter\"\xea\x05\n" +
	"\x06Policy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12H\n" +
	"\x0eobject_filters\x18\x04 \x03(\v2!.policyserverservice.ObjectFilterR\robjectFilters\x12\x10\n" +
	"\x03rpo\x18\x05 \x01(\tR\x03rpo\x12#\n" +
	"\rbackup_window\x18\x06 \x03(\tR\fbackupWindow\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02id\x12I\n" +
	"\x0eclient_filters\x18\t \x01(\v2\".policyserverservice.ClientFiltersR\rclientFilters\x12\x12\n" +
	"\x04type\x18\n" +
	" \x01(\tR\x04type\x12\x12\n" +
	"\x04port\x18\f \x01(\x05R\x04port\x12\x16\n" +
	"\x06config\x18\r \x01(\tR\x06config\x12;\n" +
	"\vdisabled_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"disabledAt\x12*\n" +
	"\x11storage_policy_id\x18\x0f \x01(\tR\x0fstoragePolicyId\x12>\n" +
	"\bcheckins\x18\x10 \x03(\v2\".policyserverservice.PolicyCheckinR\bcheckins\x12\"\n" +
	"\fdestinations\x18\x11 \x03(\tR\fdestinations\x126\n" +
	"\x05rules\x18\x13 \x03(\v2 .policyserverservice.RestoreRuleR\x05rulesJ\x04\b\a\x10\bJ\x04\b\v\x10\fJ\x04\b\x12\x10\x13R\vdestinationR\bhostnameR\fsource_store\"\x8d\x04\n" +
	"\x13CreatePolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12I\n" +
	"\x0eclient_filters\x18\x02 \x01(\v2\".policyserverservice.ClientFiltersR\rclientFilters\x12H\n" +
	"\x0eobject_filters\x18\x03 \x03(\v2!.policyserverservice.ObjectFilterR\robjectFilters\x12\x10\n" +
	"\x03rpo\x18\x04 \x01(\tR\x03rpo\x12#\n" +
	"\rbackup_window\x18\x05 \x03(\tR\fbackupWindow\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x12\n" +
	"\x04port\x18\t \x01(\x05R\x04port\x12\x16\n" +
	"\x06config\x18\n" +
	" \x01(\tR\x06config\x12;\n" +
	"\vdisabled_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"disabledAt\x12*\n" +
	"\x11storage_policy_id\x18\f \x01(\tR\x0fstoragePolicyId\x126\n" +
	"\x05rules\x18\x0e \x03(\v2 .policyserverservice.RestoreRuleR\x05rulesJ\x04\b\x06\x10\aJ\x04\b\b\x10\tJ\x04\b\r\x10\x0eR\vdestinationR\bhostnameR\fsource_store\"\xbd\x03\n" +
	"\x13UpdatePolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12I\n" +
	"\x0eclient_filters\x18\x03 \x01(\v2\".policyserverservice.ClientFiltersR\rclientFilters\x12H\n" +
	"\x0eobject_filters\x18\x04 \x03(\v2!.policyserverservice.ObjectFilterR\robjectFilters\x12\x10\n" +
	"\x03rpo\x18\x05 \x01(\tR\x03rpo\x12#\n" +
	"\rbackup_window\x18\x06 \x03(\tR\fbackupWindow\x12\x12\n" +
	"\x04port\x18\t \x01(\x05R\x04port\x12\x16\n" +
	"\x06config\x18\n" +
	" \x01(\tR\x06config\x12;\n" +
	"\vdisabled_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"disabledAt\x12*\n" +
	"\x11storage_policy_id\x18\f \x01(\tR\x0fstoragePolicyIdJ\x04\b\a\x10\bJ\x04\b\b\x10\tR\vdestinationR\bhostname\"%\n" +
	"\x13DeletePolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeletePolicyResponse2\xe9\x03\n" +
	"\rPolicyService\x12`\n" +
	"\vGetPolicies\x12'.policyserverservice.GetPoliciesRequest\x1a(.policyserverservice.GetPoliciesResponse\x12c\n" +
	"\fListPolicies\x12(.policyserverservice.ListPoliciesRequest\x1a).policyserverservice.ListPoliciesResponse\x12U\n" +
	"\fCreatePolicy\x12(.policyserverservice.CreatePolicyRequest\x1a\x1b.policyserverservice.Policy\x12U\n" +
	"\fUpdatePolicy\x12(.policyserverservice.UpdatePolicyRequest\x1a\x1b.policyserverservice.Policy\x12c\n" +
	"\fDeletePolicy\x12(.policyserverservice.DeletePolicyRequest\x1a).policyserverservice.DeletePolicyResponseB\tZ\a./protob\x06proto3"

var (
	file_api_policyserver_proto_rawDescOnce sync.Once
	file_api_policyserver_proto_rawDescData []byte
)

func file_api_policyserver_proto_rawDescGZIP() []byte {
	file_api_policyserver_proto_rawDescOnce.Do(func() {
		file_api_policyserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_policyserver_proto_rawDesc), len(file_api_policyserver_proto_rawDesc)))
	})
	return file_api_policyserver_proto_rawDescData
}

var file_api_policyserver_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_policyserver_proto_goTypes = []any{
	(*GetPoliciesRequest)(nil),    // 0: policyserverservice.GetPoliciesRequest
	(*GetPoliciesResponse)(nil),   // 1: policyserverservice.GetPoliciesResponse
	(*ListPoliciesRequest)(nil),   // 2: policyserverservice.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),  // 3: policyserverservice.ListPoliciesResponse
	(*ClientFilters)(nil),         // 4: policyserverservice.ClientFilters
	(*ObjectFilter)(nil),          // 5: policyserverservice.ObjectFilter
	(*PolicyCheckin)(nil),         // 6: policyserverservice.PolicyCheckin
	(*RestoreRule)(nil),           // 7: policyserverservice.RestoreRule
	(*Policy)(nil),                // 8: policyserverservice.Policy
	(*CreatePolicyRequest)(nil),   // 9: policyserverservice.CreatePolicyRequest
	(*UpdatePolicyRequest)(nil),   // 10: policyserverservice.UpdatePolicyRequest
	(*DeletePolicyRequest)(nil),   // 11: policyserverservice.DeletePolicyRequest
	(*DeletePolicyResponse)(nil),  // 12: policyserverservice.DeletePolicyResponse
	nil,                           // 13: policyserverservice.ClientFilters.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_api_policyserver_proto_depIdxs = []int32{
	8,  // 0: policyserverservice.GetPoliciesResponse.policies:type_name -> policyserverservice.Policy
	8,  // 1: policyserverservice.ListPoliciesResponse.policies:type_name -> policyserverservice.Policy
	13, // 2: policyserverservice.ClientFilters.labels:type_name -> policyserverservice.ClientFilters.LabelsEntry
	14, // 3: policyserverservice.PolicyCheckin.last_seen_at:type_name -> google.protobuf.Timestamp
	14, // 4: policyserverservice.Policy.created_at:type_name -> google.protobuf.Timestamp
	14, // 5: policyserverservice.Policy.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 6: policyserverservice.Policy.object_filters:type_name -> policyserverservice.ObjectFilter
	4,  // 7: policyserverservice.Policy.client_filters:type_name -> policyserverservice.ClientFilters
	14, // 8: policyserverservice.Policy.disabled_at:type_name -> google.protobuf.Timestamp
	6,  // 9: policyserverservice.Policy.checkins:type_name -> policyserverservice.PolicyCheckin
	7,  // 10: policyserverservice.Policy.rules:type_name -> policyserverservice.RestoreRule
	4,  // 11: policyserverservice.CreatePolicyRequest.client_filters:type_name -> policyserverservice.ClientFilters
	5,  // 12: policyserverservice.CreatePolicyRequest.object_filters:type_name -> policyserverservice.ObjectFilter
	14, // 13: policyserverservice.CreatePolicyRequest.disabled_at:type_name -> google.protobuf.Timestamp
	7,  // 14: policyserverservice.CreatePolicyRequest.rules:type_name -> policyserverservice.RestoreRule
	4,  // 15: policyserverservice.UpdatePolicyRequest.client_filters:type_name -> policyserverservice.ClientFilters
	5,  // 16: policyserverservice.UpdatePolicyRequest.object_filters:type_name -> policyserverservice.ObjectFilter
	14, // 17: policyserverservice.UpdatePolicyRequest.disabled_at:type_name -> google.protobuf.Timestamp
	0,  // 18: policyserverservice.PolicyService.GetPolicies:input_type -> policyserverservice.GetPoliciesRequest
	2,  // 19: policyserverservice.PolicyService.ListPolicies:input_type -> policyserverservice.ListPoliciesRequest
	9,  // 20: policyserverservice.PolicyService.CreatePolicy:input_type -> policyserverservice.CreatePolicyRequest
	10, // 21: policyserverservice.PolicyService.UpdatePolicy:input_type -> policyserverservice.UpdatePolicyRequest
	11, // 22: policyserverservice.PolicyService.DeletePolicy:input_type -> policyserverservice.DeletePolicyRequest
	1,  // 23: policyserverservice.PolicyService.GetPolicies:output_type -> policyserverservice.GetPoliciesResponse
	3,  // 24: policyserverservice.PolicyService.ListPolicies:output_type -> policyserverservice.ListPoliciesResponse
	8,  // 25: policyserverservice.PolicyService.CreatePolicy:output_type -> policyserverservice.Policy
	8,  // 26: policyserverservice.PolicyService.UpdatePolicy:output_type -> policyserverservice.Policy
	12, // 27: policyserverservice.PolicyService.DeletePolicy:output_type -> policyserverservice.DeletePolicyResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_policyserver_proto_init() }
func file_api_policyserver_proto_init() {
	if File_api_policyserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_policyserver_proto_rawDesc), len(file_api_policyserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_policyserver_proto_goTypes,
		DependencyIndexes: file_api_policyserver_proto_depIdxs,
		MessageInfos:      file_api_policyserver_proto_msgTypes,
	}.Build()
	File_api_policyserver_proto = out.File
	file_api_policyserver_proto_goTypes = nil
	file_api_policyserver_proto_depIdxs = nil
}
