// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/policyserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoliciesRequest) Reset() {
	*x = GetPoliciesRequest{}
	mi := &file_api_policyserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoliciesRequest) ProtoMessage() {}

func (x *GetPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoliciesRequest.ProtoReflect.Descriptor instead.
func (*GetPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{0}
}

type GetPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*Policy              `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoliciesResponse) Reset() {
	*x = GetPoliciesResponse{}
	mi := &file_api_policyserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoliciesResponse) ProtoMessage() {}

func (x *GetPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoliciesResponse.ProtoReflect.Descriptor instead.
func (*GetPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{1}
}

func (x *GetPoliciesResponse) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type ObjectFilter struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Path    string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Include []string               `protobuf:"bytes,2,rep,name=include,proto3" json:"include,omitempty"`
	Exclude []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	// policy-server-computed, deterministic (see Policy.id). Not present in
	// the on-disk policy JSON schema.
	Id            string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectFilter) Reset() {
	*x = ObjectFilter{}
	mi := &file_api_policyserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectFilter) ProtoMessage() {}

func (x *ObjectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectFilter.ProtoReflect.Descriptor instead.
func (*ObjectFilter) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectFilter) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ObjectFilter) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *ObjectFilter) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *ObjectFilter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ObjectFilters []*ObjectFilter        `protobuf:"bytes,4,rep,name=object_filters,json=objectFilters,proto3" json:"object_filters,omitempty"`
	// Duration string, e.g. "24h" (time.ParseDuration format). policy-server
	// never parses or evaluates this -- opaque pass-through data.
	Rpo string `protobuf:"bytes,5,opt,name=rpo,proto3" json:"rpo,omitempty"`
	// List of cron expressions (5-field). policy-server never parses or
	// evaluates these -- opaque pass-through data.
	BackupWindow []string `protobuf:"bytes,6,rep,name=backup_window,json=backupWindow,proto3" json:"backup_window,omitempty"`
	Destination  string   `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	// policy-server-computed, deterministic from the policy file's name --
	// stable across reloads, changes only if the file is renamed. Not
	// present in the on-disk policy JSON schema.
	Id            string `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_api_policyserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_api_policyserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_api_policyserver_proto_rawDescGZIP(), []int{3}
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Policy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Policy) GetObjectFilters() []*ObjectFilter {
	if x != nil {
		return x.ObjectFilters
	}
	return nil
}

func (x *Policy) GetRpo() string {
	if x != nil {
		return x.Rpo
	}
	return ""
}

func (x *Policy) GetBackupWindow() []string {
	if x != nil {
		return x.BackupWindow
	}
	return nil
}

func (x *Policy) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_policyserver_proto protoreflect.FileDescriptor

const file_api_policyserver_proto_rawDesc = "" +
	"\n" +
	"\x16api/policyserver.proto\x12\x13policyserverservice\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12GetPoliciesRequest\"N\n" +
	"\x13GetPoliciesResponse\x127\n" +
	"\bpolicies\x18\x01 \x03(\v2\x1b.policyserverservice.PolicyR\bpolicies\"f\n" +
	"\fObjectFilter\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\ainclude\x18\x02 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"\xc5\x02\n" +
	"\x06Policy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12H\n" +
	"\x0eobject_filters\x18\x04 \x03(\v2!.policyserverservice.ObjectFilterR\robjectFilters\x12\x10\n" +
	"\x03rpo\x18\x05 \x01(\tR\x03rpo\x12#\n" +
	"\rbackup_window\x18\x06 \x03(\tR\fbackupWindow\x12 \n" +
	"\vdestination\x18\a \x01(\tR\vdestination\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02id2q\n" +
	"\rPolicyService\x12`\n" +
	"\vGetPolicies\x12'.policyserverservice.GetPoliciesRequest\x1a(.policyserverservice.GetPoliciesResponseB\tZ\a./protob\x06proto3"

var (
	file_api_policyserver_proto_rawDescOnce sync.Once
	file_api_policyserver_proto_rawDescData []byte
)

func file_api_policyserver_proto_rawDescGZIP() []byte {
	file_api_policyserver_proto_rawDescOnce.Do(func() {
		file_api_policyserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_policyserver_proto_rawDesc), len(file_api_policyserver_proto_rawDesc)))
	})
	return file_api_policyserver_proto_rawDescData
}

var file_api_policyserver_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_policyserver_proto_goTypes = []any{
	(*GetPoliciesRequest)(nil),    // 0: policyserverservice.GetPoliciesRequest
	(*GetPoliciesResponse)(nil),   // 1: policyserverservice.GetPoliciesResponse
	(*ObjectFilter)(nil),          // 2: policyserverservice.ObjectFilter
	(*Policy)(nil),                // 3: policyserverservice.Policy
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_api_policyserver_proto_depIdxs = []int32{
	3, // 0: policyserverservice.GetPoliciesResponse.policies:type_name -> policyserverservice.Policy
	4, // 1: policyserverservice.Policy.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: policyserverservice.Policy.updated_at:type_name -> google.protobuf.Timestamp
	2, // 3: policyserverservice.Policy.object_filters:type_name -> policyserverservice.ObjectFilter
	0, // 4: policyserverservice.PolicyService.GetPolicies:input_type -> policyserverservice.GetPoliciesRequest
	1, // 5: policyserverservice.PolicyService.GetPolicies:output_type -> policyserverservice.GetPoliciesResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_policyserver_proto_init() }
func file_api_policyserver_proto_init() {
	if File_api_policyserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_policyserver_proto_rawDesc), len(file_api_policyserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_policyserver_proto_goTypes,
		DependencyIndexes: file_api_policyserver_proto_depIdxs,
		MessageInfos:      file_api_policyserver_proto_msgTypes,
	}.Build()
	File_api_policyserver_proto = out.File
	file_api_policyserver_proto_goTypes = nil
	file_api_policyserver_proto_depIdxs = nil
}
