// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/restore.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUuid      string                 `protobuf:"bytes,1,opt,name=file_uuid,json=fileUuid,proto3" json:"file_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_api_restore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_restore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_api_restore_proto_rawDescGZIP(), []int{0}
}

func (x *RestoreRequest) GetFileUuid() string {
	if x != nil {
		return x.FileUuid
	}
	return ""
}

type RestoreEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RestoreEvent_Meta
	//	*RestoreEvent_Chunk
	Payload       isRestoreEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreEvent) Reset() {
	*x = RestoreEvent{}
	mi := &file_api_restore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreEvent) ProtoMessage() {}

func (x *RestoreEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_restore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreEvent.ProtoReflect.Descriptor instead.
func (*RestoreEvent) Descriptor() ([]byte, []int) {
	return file_api_restore_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreEvent) GetPayload() isRestoreEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RestoreEvent) GetMeta() *RestoreFileMeta {
	if x != nil {
		if x, ok := x.Payload.(*RestoreEvent_Meta); ok {
			return x.Meta
		}
	}
	return nil
}

func (x *RestoreEvent) GetChunk() *RestoreChunk {
	if x != nil {
		if x, ok := x.Payload.(*RestoreEvent_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isRestoreEvent_Payload interface {
	isRestoreEvent_Payload()
}

type RestoreEvent_Meta struct {
	Meta *RestoreFileMeta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type RestoreEvent_Chunk struct {
	Chunk *RestoreChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*RestoreEvent_Meta) isRestoreEvent_Payload() {}

func (*RestoreEvent_Chunk) isRestoreEvent_Payload() {}

type RestoreFileMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Size             int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	ChunkCount       int32                  `protobuf:"varint,2,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	ExpectedChecksum []byte                 `protobuf:"bytes,3,opt,name=expected_checksum,json=expectedChecksum,proto3" json:"expected_checksum,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestoreFileMeta) Reset() {
	*x = RestoreFileMeta{}
	mi := &file_api_restore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreFileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreFileMeta) ProtoMessage() {}

func (x *RestoreFileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_restore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreFileMeta.ProtoReflect.Descriptor instead.
func (*RestoreFileMeta) Descriptor() ([]byte, []int) {
	return file_api_restore_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreFileMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RestoreFileMeta) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *RestoreFileMeta) GetExpectedChecksum() []byte {
	if x != nil {
		return x.ExpectedChecksum
	}
	return nil
}

type RestoreChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreChunk) Reset() {
	*x = RestoreChunk{}
	mi := &file_api_restore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreChunk) ProtoMessage() {}

func (x *RestoreChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_restore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreChunk.ProtoReflect.Descriptor instead.
func (*RestoreChunk) Descriptor() ([]byte, []int) {
	return file_api_restore_proto_rawDescGZIP(), []int{3}
}

func (x *RestoreChunk) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *RestoreChunk) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *RestoreChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RestoreChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

var File_api_restore_proto protoreflect.FileDescriptor

const file_api_restore_proto_rawDesc = "" +
	"\n" +
	"\x11api/restore.proto\x12\x0erestoreservice\"-\n" +
	"\x0eRestoreRequest\x12\x1b\n" +
	"\tfile_uuid\x18\x01 \x01(\tR\bfileUuid\"\x86\x01\n" +
	"\fRestoreEvent\x125\n" +
	"\x04meta\x18\x01 \x01(\v2\x1f.restoreservice.RestoreFileMetaH\x00R\x04meta\x124\n" +
	"\x05chunk\x18\x02 \x01(\v2\x1c.restoreservice.RestoreChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"s\n" +
	"\x0fRestoreFileMeta\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x1f\n" +
	"\vchunk_count\x18\x02 \x01(\x05R\n" +
	"chunkCount\x12+\n" +
	"\x11expected_checksum\x18\x03 \x01(\fR\x10expectedChecksum\"^\n" +
	"\fRestoreChunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof2_\n" +
	"\x0eRestoreService\x12M\n" +
	"\vRestoreFile\x12\x1e.restoreservice.RestoreRequest\x1a\x1c.restoreservice.RestoreEvent0\x01B\tZ\a./protob\x06proto3"

var (
	file_api_restore_proto_rawDescOnce sync.Once
	file_api_restore_proto_rawDescData []byte
)

func file_api_restore_proto_rawDescGZIP() []byte {
	file_api_restore_proto_rawDescOnce.Do(func() {
		file_api_restore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_restore_proto_rawDesc), len(file_api_restore_proto_rawDesc)))
	})
	return file_api_restore_proto_rawDescData
}

var file_api_restore_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_restore_proto_goTypes = []any{
	(*RestoreRequest)(nil),  // 0: restoreservice.RestoreRequest
	(*RestoreEvent)(nil),    // 1: restoreservice.RestoreEvent
	(*RestoreFileMeta)(nil), // 2: restoreservice.RestoreFileMeta
	(*RestoreChunk)(nil),    // 3: restoreservice.RestoreChunk
}
var file_api_restore_proto_depIdxs = []int32{
	2, // 0: restoreservice.RestoreEvent.meta:type_name -> restoreservice.RestoreFileMeta
	3, // 1: restoreservice.RestoreEvent.chunk:type_name -> restoreservice.RestoreChunk
	0, // 2: restoreservice.RestoreService.RestoreFile:input_type -> restoreservice.RestoreRequest
	1, // 3: restoreservice.RestoreService.RestoreFile:output_type -> restoreservice.RestoreEvent
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_restore_proto_init() }
func file_api_restore_proto_init() {
	if File_api_restore_proto != nil {
		return
	}
	file_api_restore_proto_msgTypes[1].OneofWrappers = []any{
		(*RestoreEvent_Meta)(nil),
		(*RestoreEvent_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_restore_proto_rawDesc), len(file_api_restore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_restore_proto_goTypes,
		DependencyIndexes: file_api_restore_proto_depIdxs,
		MessageInfos:      file_api_restore_proto_msgTypes,
	}.Build()
	File_api_restore_proto = out.File
	file_api_restore_proto_goTypes = nil
	file_api_restore_proto_depIdxs = nil
}
