// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/storagestatus.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageStatusService_ReportStorageStatus_FullMethodName = "/storagestatusservice.StorageStatusService/ReportStorageStatus"
)

// StorageStatusServiceClient is the client API for StorageStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageStatusService is the second inbound gRPC surface on api-server
// (alongside JobStatusService, same mTLS port). Each bwfs server posts one
// report a minute; api-server keeps only the latest per (policy_id, reporting
// host) in memory and serves it to the web UI. Restricted to the "store" role.
// The reporting host is taken from the verified mTLS peer certificate, never
// from the payload.
type StorageStatusServiceClient interface {
	ReportStorageStatus(ctx context.Context, in *ReportStorageStatusRequest, opts ...grpc.CallOption) (*ReportStorageStatusResponse, error)
}

type storageStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageStatusServiceClient(cc grpc.ClientConnInterface) StorageStatusServiceClient {
	return &storageStatusServiceClient{cc}
}

func (c *storageStatusServiceClient) ReportStorageStatus(ctx context.Context, in *ReportStorageStatusRequest, opts ...grpc.CallOption) (*ReportStorageStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportStorageStatusResponse)
	err := c.cc.Invoke(ctx, StorageStatusService_ReportStorageStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageStatusServiceServer is the server API for StorageStatusService service.
// All implementations must embed UnimplementedStorageStatusServiceServer
// for forward compatibility.
//
// StorageStatusService is the second inbound gRPC surface on api-server
// (alongside JobStatusService, same mTLS port). Each bwfs server posts one
// report a minute; api-server keeps only the latest per (policy_id, reporting
// host) in memory and serves it to the web UI. Restricted to the "store" role.
// The reporting host is taken from the verified mTLS peer certificate, never
// from the payload.
type StorageStatusServiceServer interface {
	ReportStorageStatus(context.Context, *ReportStorageStatusRequest) (*ReportStorageStatusResponse, error)
	mustEmbedUnimplementedStorageStatusServiceServer()
}

// UnimplementedStorageStatusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageStatusServiceServer struct{}

func (UnimplementedStorageStatusServiceServer) ReportStorageStatus(context.Context, *ReportStorageStatusRequest) (*ReportStorageStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStorageStatus not implemented")
}
func (UnimplementedStorageStatusServiceServer) mustEmbedUnimplementedStorageStatusServiceServer() {}
func (UnimplementedStorageStatusServiceServer) testEmbeddedByValue()                              {}

// UnsafeStorageStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageStatusServiceServer will
// result in compilation errors.
type UnsafeStorageStatusServiceServer interface {
	mustEmbedUnimplementedStorageStatusServiceServer()
}

func RegisterStorageStatusServiceServer(s grpc.ServiceRegistrar, srv StorageStatusServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageStatusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageStatusService_ServiceDesc, srv)
}

func _StorageStatusService_ReportStorageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportStorageStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageStatusServiceServer).ReportStorageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageStatusService_ReportStorageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageStatusServiceServer).ReportStorageStatus(ctx, req.(*ReportStorageStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageStatusService_ServiceDesc is the grpc.ServiceDesc for StorageStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storagestatusservice.StorageStatusService",
	HandlerType: (*StorageStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStorageStatus",
			Handler:    _StorageStatusService_ReportStorageStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/storagestatus.proto",
}
