// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/storagestatus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportStorageStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the storage policy this bwfs process serves (agent passes it via
	// --policy-id).
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Port     int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// "serving" while the process is up.
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Total and used bytes of the filesystem holding the store root.
	DiskTotalBytes uint64 `protobuf:"varint,4,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DiskUsedBytes  uint64 `protobuf:"varint,5,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	// Currently open gRPC client connections.
	ActiveConnections int32 `protobuf:"varint,6,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	// Backup jobs with activity that have not yet been finalized.
	InProgressJobs int32                  `protobuf:"varint,7,opt,name=in_progress_jobs,json=inProgressJobs,proto3" json:"in_progress_jobs,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ReportedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportStorageStatusRequest) Reset() {
	*x = ReportStorageStatusRequest{}
	mi := &file_api_storagestatus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStorageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStorageStatusRequest) ProtoMessage() {}

func (x *ReportStorageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_storagestatus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStorageStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStorageStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_storagestatus_proto_rawDescGZIP(), []int{0}
}

func (x *ReportStorageStatusRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *ReportStorageStatusRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ReportStorageStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportStorageStatusRequest) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *ReportStorageStatusRequest) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *ReportStorageStatusRequest) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ReportStorageStatusRequest) GetInProgressJobs() int32 {
	if x != nil {
		return x.InProgressJobs
	}
	return 0
}

func (x *ReportStorageStatusRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ReportStorageStatusRequest) GetReportedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportedAt
	}
	return nil
}

type ReportStorageStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportStorageStatusResponse) Reset() {
	*x = ReportStorageStatusResponse{}
	mi := &file_api_storagestatus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStorageStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStorageStatusResponse) ProtoMessage() {}

func (x *ReportStorageStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_storagestatus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStorageStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStorageStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_storagestatus_proto_rawDescGZIP(), []int{1}
}

var File_api_storagestatus_proto protoreflect.FileDescriptor

const file_api_storagestatus_proto_rawDesc = "" +
	"\n" +
	"\x17api/storagestatus.proto\x12\x14storagestatusservice\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x02\n" +
	"\x1aReportStorageStatusRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12(\n" +
	"\x10disk_total_bytes\x18\x04 \x01(\x04R\x0ediskTotalBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\x05 \x01(\x04R\rdiskUsedBytes\x12-\n" +
	"\x12active_connections\x18\x06 \x01(\x05R\x11activeConnections\x12(\n" +
	"\x10in_progress_jobs\x18\a \x01(\x05R\x0einProgressJobs\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x03R\ruptimeSeconds\x12;\n" +
	"\vreported_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reportedAt\"\x1d\n" +
	"\x1bReportStorageStatusResponse2\x92\x01\n" +
	"\x14StorageStatusService\x12z\n" +
	"\x13ReportStorageStatus\x120.storagestatusservice.ReportStorageStatusRequest\x1a1.storagestatusservice.ReportStorageStatusResponseB\tZ\a./protob\x06proto3"

var (
	file_api_storagestatus_proto_rawDescOnce sync.Once
	file_api_storagestatus_proto_rawDescData []byte
)

func file_api_storagestatus_proto_rawDescGZIP() []byte {
	file_api_storagestatus_proto_rawDescOnce.Do(func() {
		file_api_storagestatus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_storagestatus_proto_rawDesc), len(file_api_storagestatus_proto_rawDesc)))
	})
	return file_api_storagestatus_proto_rawDescData
}

var file_api_storagestatus_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_storagestatus_proto_goTypes = []any{
	(*ReportStorageStatusRequest)(nil),  // 0: storagestatusservice.ReportStorageStatusRequest
	(*ReportStorageStatusResponse)(nil), // 1: storagestatusservice.ReportStorageStatusResponse
	(*timestamppb.Timestamp)(nil),       // 2: google.protobuf.Timestamp
}
var file_api_storagestatus_proto_depIdxs = []int32{
	2, // 0: storagestatusservice.ReportStorageStatusRequest.reported_at:type_name -> google.protobuf.Timestamp
	0, // 1: storagestatusservice.StorageStatusService.ReportStorageStatus:input_type -> storagestatusservice.ReportStorageStatusRequest
	1, // 2: storagestatusservice.StorageStatusService.ReportStorageStatus:output_type -> storagestatusservice.ReportStorageStatusResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_storagestatus_proto_init() }
func file_api_storagestatus_proto_init() {
	if File_api_storagestatus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_storagestatus_proto_rawDesc), len(file_api_storagestatus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_storagestatus_proto_goTypes,
		DependencyIndexes: file_api_storagestatus_proto_depIdxs,
		MessageInfos:      file_api_storagestatus_proto_msgTypes,
	}.Build()
	File_api_storagestatus_proto = out.File
	file_api_storagestatus_proto_goTypes = nil
	file_api_storagestatus_proto_depIdxs = nil
}
