services:
  ca:
    build:
      context: ..
      dockerfile: demo/ca/Dockerfile
    volumes:
      - ca-data:/home/step
      - client-manager-data:/data/client-manager
      - ./ca/clientmanager-local.conf:/data/client-manager-conf/local.conf:ro
    environment:
      - MP_CONFIG_PATH=/data/client-manager-conf
    restart: unless-stopped

  issuer:
    build:
      context: ..
      dockerfile: demo/issuer/Dockerfile
    depends_on:
      - ca
    volumes:
      - issuer-data:/data
      - ./local.conf:/data/local.conf:ro
      - client-manager-data:/data/client-manager
      - ca-data:/ca-data:ro
    environment:
      - MP_CONFIG_PATH=/data
    restart: unless-stopped

  catalog:
    build:
      context: ..
      dockerfile: deploy/control-plane/catalog/Dockerfile
    depends_on:
      - ca
      - issuer
    volumes:
      - catalog-data:/data
      - ./local.conf:/data/local.conf:ro
    environment:
      - MP_CONFIG_PATH=/data
      - MP_CERT_TOKEN=${MP_CERT_TOKEN:-}
      - STORAGE_PATH=/data/storage
    restart: unless-stopped

  policy-server:
    build:
      context: ..
      dockerfile: deploy/control-plane/policy-server/Dockerfile
    depends_on:
      - ca
      - issuer
    volumes:
      - policy-server-data:/data
      - ./local.conf:/data/local.conf:ro
      - ./policy-server/policies:/data/policies
    environment:
      - MP_CONFIG_PATH=/data
      - MP_CERT_TOKEN=${MP_CERT_TOKEN:-}
    restart: unless-stopped

  database:
    build:
      context: ..
      dockerfile: demo/backup-host/Dockerfile
    depends_on:
      - ca
      - issuer
    volumes:
      - database-data:/data
      - ./local.conf:/data/local.conf:ro
      - ./sample-data/audit:/var/log/audit:ro
      - ./sample-data/db:/var/lib/dbdata:ro
    environment:
      - MP_CONFIG_PATH=/data
      - MP_CERT_TOKEN=${MP_CERT_TOKEN:-}
    restart: unless-stopped

  webserver:
    build:
      context: ..
      dockerfile: demo/backup-host/Dockerfile
    depends_on:
      - ca
      - issuer
    volumes:
      - webserver-data:/data
      - ./local.conf:/data/local.conf:ro
      - ./sample-data/audit:/var/log/audit:ro
      - ./sample-data/web:/var/www/html:ro
    environment:
      - MP_CONFIG_PATH=/data
      - MP_CERT_TOKEN=${MP_CERT_TOKEN:-}
    restart: unless-stopped

  store:
    build:
      context: ..
      dockerfile: demo/backup-host/Dockerfile
    depends_on:
      - ca
      - issuer
      - catalog
    volumes:
      - store-data:/data
      - ./local.conf:/data/local.conf:ro
    environment:
      - MP_CONFIG_PATH=/data
      - MP_CERT_TOKEN=${MP_CERT_TOKEN:-}
      - STORAGE_PATH=/data/storage
    restart: unless-stopped

volumes:
  ca-data:
  client-manager-data:
  issuer-data:
  catalog-data:
  policy-server-data:
  database-data:
  webserver-data:
  store-data:
