default_port=8080
default_streams=4
logfolder=/var/log/miniprotector
ca_host=ca:9000
issuer_host=issuer
issuer_port=9200
catalog_host=catalog
catalog_port=15723
policy_server_host=policy-server
ReconcileIntervalSec=30
BootstrapCertRefreshIntervalSec=86400
OperatingCertFetchIntervalSec=900
JobTimeoutSec=30
var_path=/data/client-manager
ConnectionTimeOutSec=30
FileLockTimeoutSec=30
