default_port=15722
default_streams=4
log_dir=/tmp/log
ClientHashQueryBatchSize=10
ConnectionTimeOutSec=30
FileLockTimeoutSec=300
StopStreamOnFileError=true
JobTimeoutSec=30
catalog_host=catalog.internal
catalog_port=15723
